/* Generated by Nim Compiler v0.15.0 */
/*   (c) 2016 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.15.0/nim/lib -o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/server.o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/server.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <unistd.h>
#include <errno.h>
typedef struct Socketimpl158406 Socketimpl158406;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47705 Cell47705;
typedef struct Cellseq47721 Cellseq47721;
typedef struct Gcheap50218 Gcheap50218;
typedef struct Gcstack50216 Gcstack50216;
typedef struct Memregion29886 Memregion29886;
typedef struct Smallchunk29840 Smallchunk29840;
typedef struct Llchunk29880 Llchunk29880;
typedef struct Bigchunk29842 Bigchunk29842;
typedef struct Intset29814 Intset29814;
typedef struct Trunk29810 Trunk29810;
typedef struct Avlnode29884 Avlnode29884;
typedef struct Gcstat50214 Gcstat50214;
typedef struct Cellset47717 Cellset47717;
typedef struct Pagedesc47713 Pagedesc47713;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Basechunk29838 Basechunk29838;
typedef struct Freecell29830 Freecell29830;
typedef NU8 Tnimkind3403;
typedef NU8 Tnimtypeflag3409Set;
typedef N_NIMCALL_PTR(void, TY3489) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3403 kind;
Tnimtypeflag3409Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
typedef NU8 Tnimnodekind3405;
struct  TNimNode  {
Tnimnodekind3405 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, Globalmarkerproc56202) (void);
typedef NU8 Domain147604;
typedef NU8 Socktype147606;
typedef NU8 Protocol147608;
struct  Cell47705  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47721  {
NI len;
NI cap;
Cell47705** d;
};
typedef Smallchunk29840* TY29901[512];
typedef Trunk29810* Trunkbuckets29812[256];
struct  Intset29814  {
Trunkbuckets29812 data;
};
struct  Memregion29886  {
NI minlargeobj;
NI maxlargeobj;
TY29901 freesmallchunks;
Llchunk29880* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29842* freechunkslist;
Intset29814 chunkstarts;
Avlnode29884* root;
Avlnode29884* deleted;
Avlnode29884* last;
Avlnode29884* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat50214  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47717  {
NI counter;
NI max;
Pagedesc47713* head;
Pagedesc47713** data;
};
struct  Gcheap50218  {
Gcstack50216* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47721 zct;
Cellseq47721 decstack;
Cellseq47721 tempstack;
NI recgclock;
Memregion29886 region;
Gcstat50214 stat;
Cellset47717 marked;
Cellseq47721 additionalroots;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NIM_CHAR TY158420[4001];
struct  Socketimpl158406  {
int fd;
NIM_BOOL isbuffered;
union{
struct {TY158420 buffer;
NI currpos;
NI buflen;
} S1;
} isbufferedU;
NI32 lasterror;
Domain147604 domain;
Socktype147606 socktype;
Protocol147608 protocol;
};
struct  Gcstack50216  {
Gcstack50216* prev;
Gcstack50216* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk29838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29840  {
  Basechunk29838 Sup;
Smallchunk29840* next;
Smallchunk29840* prev;
Freecell29830* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29880  {
NI size;
NI acc;
Llchunk29880* next;
};
struct  Bigchunk29842  {
  Basechunk29838 Sup;
Bigchunk29842* next;
Bigchunk29842* prev;
NI align;
NF data;
};
typedef NI TY29819[8];
struct  Trunk29810  {
Trunk29810* next;
NI key;
TY29819 bits;
};
typedef Avlnode29884* TY29891[2];
struct  Avlnode29884  {
TY29891 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47713  {
Pagedesc47713* next;
NI key;
TY29819 bits;
};
struct  Freecell29830  {
Freecell29830* next;
NI zerofield;
};
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
N_NIMCALL(void, T249322247_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(Globalmarkerproc56202 markerproc0);
N_NIMCALL(Socketimpl158406*, newsocket_159009_170061329)(Domain147604 domain0, Socktype147606 socktype0, Protocol147608 protocol0, NIM_BOOL buffered0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell47705*, usrtocell_51840_1689653243)(void* usr0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21601_1689653243)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_53001_1689653243)(Cell47705* c0);
N_NOINLINE(void, addzct_51817_1689653243)(Cellseq47721* s0, Cell47705* c0);
N_NIMCALL(void, bindaddr_159808_170061329)(Socketimpl158406* socket0, NU16 port0, NimStringDesc* address0);
N_NIMCALL(NI, sendto_163849_170061329)(Socketimpl158406* socket0, NimStringDesc* address0, NU16 port0, NimStringDesc* data0);
N_NIMCALL(NI32, getsocketerror_159201_170061329)(Socketimpl158406* socket0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x0);
static N_INLINE(void, initStackBottomWith)(void* locals0);
N_NOINLINE(void, setStackBottom)(void* thestackbottom0);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, serverInit000)(void);
NIM_EXTERNC N_NOINLINE(void, serverDatInit000)(void);
STRING_LITERAL(T249322247_3, "", 0);
STRING_LITERAL(T249322247_4, "127.0.0.1", 9);
STRING_LITERAL(T249322247_5, "\000\000\000\000\366(\274?\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\200?333\276\037\205k?\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\200?\000\000\321\"\253?\037"
"\205k?{\024.\276\000\000\000\000\000\000\000\000\000\000\000\000\000\000\200?\000\000", 88);
STRING_LITERAL(T249322247_6, "Slept", 5);
Socketimpl158406* socket_167004_249322247;
extern TNimType NTI158408; /* Socket */
extern TFrame* frameptr_18836_1689653243;
extern Gcheap50218 gch_50258_1689653243;
NI result_167007_249322247;
NI32 e_167008_249322247;
N_NIMCALL(void, T249322247_2)(void) {
	nimGCvisit((void*)socket_167004_249322247, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18836_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18836_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18836_1689653243;
	frameptr_18836_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21601_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18836_1689653243 = (*frameptr_18836_1689653243).prev;
}

static N_INLINE(Cell47705*, usrtocell_51840_1689653243)(void* usr0) {
	Cell47705* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell47705*)0;
	nimln(134, "gc.nim");
	result0 = ((Cell47705*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell47705))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_53001_1689653243)(Cell47705* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(214, "gc.nim");
	addzct_51817_1689653243((&gch_50258_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(274, "gc.nim");
	{
		Cell47705* c0;
		nimln(347, "system.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(275, "gc.nim");
		c0 = usrtocell_51840_1689653243(src0);
		nimln(182, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(277, "gc.nim");
	{
		Cell47705* c0;
		nimln(347, "system.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(278, "gc.nim");
		c0 = usrtocell_51840_1689653243((*dest0));
		nimln(279, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c0).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(280, "gc.nim");
			rtladdzct_53001_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(281, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals0) {
	setStackBottom(locals0);
}
void PreMainInner() {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_osDatInit000();
	stdlib_nativesocketsDatInit000();
	stdlib_etcprivDatInit000();
	stdlib_hashesDatInit000();
	stdlib_setsDatInit000();
	stdlib_netDatInit000();
	serverDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_osInit000();
	stdlib_nativesocketsInit000();
	stdlib_etcprivInit000();
	stdlib_hashesInit000();
	stdlib_setsInit000();
	stdlib_netInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	serverInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, serverInit000)(void) {
	nimfr("server", "server.nim")
nimRegisterGlobalMarker(T249322247_2);
	nimln(4, "server.nim");
	asgnRefNoCycle((void**) (&socket_167004_249322247), newsocket_159009_170061329(((Domain147604) 2), ((Socktype147606) 2), ((Protocol147608) 17), NIM_TRUE));
	nimln(5, "server.nim");
	bindaddr_159808_170061329(socket_167004_249322247, ((NU16) 0), ((NimStringDesc*) &T249322247_3));
	{
		nimln(7, "server.nim");
		while (1) {
			NimStringDesc* LOC8;
			result_167007_249322247 = 0;
			nimln(8, "server.nim");
			result_167007_249322247 = sendto_163849_170061329(socket_167004_249322247, ((NimStringDesc*) &T249322247_4), ((NU16) 58504), ((NimStringDesc*) &T249322247_5));
			nimln(9, "server.nim");
			{
				NimStringDesc* LOC7;
				if (!(result_167007_249322247 == ((NI) -1))) goto LA5;
				e_167008_249322247 = 0;
				nimln(10, "server.nim");
				e_167008_249322247 = getsocketerror_159201_170061329(socket_167004_249322247);
				nimln(11, "server.nim");
				LOC7 = (NimStringDesc*)0;
				LOC7 = nimIntToStr(e_167008_249322247);
				printf("%s\012", LOC7? (LOC7)->data:"nil");
				fflush(stdout);
			}
			LA5: ;
			nimln(12, "server.nim");
			LOC8 = (NimStringDesc*)0;
			LOC8 = nimIntToStr(result_167007_249322247);
			printf("%s\012", LOC8? (LOC8)->data:"nil");
			fflush(stdout);
			nimln(13, "server.nim");
			{
				int LOC11;
				NimStringDesc* LOC14;
				nimln(347, "system.nim");
				nimln(13, "server.nim");
				LOC11 = (int)0;
				LOC11 = usleep(((NI) 1000000));
				if (!!((LOC11 == ((NI32) 0)))) goto LA12;
				nimln(14, "server.nim");
				LOC14 = (NimStringDesc*)0;
				LOC14 = nimIntToStr(((NI) (errno)));
				printf("%s\012", LOC14? (LOC14)->data:"nil");
				fflush(stdout);
			}
			goto LA9;
			LA12: ;
			{
				nimln(16, "server.nim");
				printf("%s\012", ((NimStringDesc*) &T249322247_6)? (((NimStringDesc*) &T249322247_6))->data:"nil");
				fflush(stdout);
			}
			LA9: ;
		}
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, serverDatInit000)(void) {
}

