/* Generated by Nim Compiler v0.15.0 */
/*   (c) 2016 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.15.0/nim/lib -o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/stdlib_math.o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/stdlib_math.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <math.h>
typedef NU8 Floatclass101611;
N_NIMCALL(NI, binom_101402_1009420244)(NI n0, NI k0);
N_NIMCALL(NI, mulInt)(NI a0, NI b0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
static N_INLINE(NI, divInt)(NI a0, NI b0);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21601_1689653243)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, fac_101426_1009420244)(NI n0);
N_NIMCALL(Floatclass101611, classify_101619_1009420244)(NF x0);
N_NIMCALL(NIM_BOOL, ispoweroftwo_101625_1009420244)(NI x0);
N_NIMCALL(NI, nextpoweroftwo_101629_1009420244)(NI x0);
N_NIMCALL(NI, countbits32_102219_1009420244)(NI32 n0);
extern TFrame* frameptr_18836_1689653243;

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, divInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		if (!(b0 == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (NIM_BOOL)0;
		LOC7 = (a0 == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b0 == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result0 = (NI)(a0 / b0);
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18836_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18836_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18836_1689653243;
	frameptr_18836_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21601_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18836_1689653243 = (*frameptr_18836_1689653243).prev;
}

N_NIMCALL(NI, binom_101402_1009420244)(NI n0, NI k0) {
	NI result0;
	nimfr("binom", "math.nim")
{	result0 = (NI)0;
	nimln(26, "math.nim");
	{
		if (!(k0 <= ((NI) 0))) goto LA3;
		result0 = ((NI) 1);
		goto BeforeRet;
	}
	LA3: ;
	nimln(27, "math.nim");
	{
		NI T1009420244_2;
		NI T1009420244_3;
		nimln(355, "system.nim");
		nimln(27, "math.nim");
		T1009420244_2 = mulInt(((NI) 2), k0);
		if (!(n0 < (NI)(T1009420244_2))) goto LA7;
		T1009420244_3 = subInt(n0, k0);
		result0 = binom_101402_1009420244(n0, (NI)(T1009420244_3));
		goto BeforeRet;
	}
	LA7: ;
	nimln(28, "math.nim");
	result0 = n0;
	{
		NI i_101418_1009420244;
		NI res_101422_1009420244;
		i_101418_1009420244 = (NI)0;
		nimln(1887, "system.nim");
		res_101422_1009420244 = ((NI) 2);
		{
			nimln(1888, "system.nim");
			while (1) {
				NI T1009420244_4;
				NI T1009420244_5;
				NI T1009420244_6;
				NI T1009420244_7;
				NI T1009420244_8;
				if (!(res_101422_1009420244 <= k0)) goto LA11;
				nimln(1889, "system.nim");
				i_101418_1009420244 = res_101422_1009420244;
				nimln(30, "math.nim");
				T1009420244_4 = addInt(n0, ((NI) 1));
				T1009420244_5 = subInt((NI)(T1009420244_4), i_101418_1009420244);
				T1009420244_6 = mulInt(result0, (NI)(T1009420244_5));
				T1009420244_7 = divInt((NI)(T1009420244_6), i_101418_1009420244);
				result0 = (NI)(T1009420244_7);
				nimln(1903, "system.nim");
				T1009420244_8 = addInt(res_101422_1009420244, ((NI) 1));
				res_101422_1009420244 = (NI)(T1009420244_8);
			} LA11: ;
		}
	}
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NI, fac_101426_1009420244)(NI n0) {
	NI result0;
	nimfr("fac", "math.nim")
	result0 = (NI)0;
	nimln(34, "math.nim");
	result0 = ((NI) 1);
	{
		NI i_101441_1009420244;
		NI res_101445_1009420244;
		i_101441_1009420244 = (NI)0;
		nimln(1887, "system.nim");
		res_101445_1009420244 = ((NI) 2);
		{
			nimln(1888, "system.nim");
			while (1) {
				NI T1009420244_9;
				NI T1009420244_10;
				if (!(res_101445_1009420244 <= n0)) goto LA3;
				nimln(1889, "system.nim");
				i_101441_1009420244 = res_101445_1009420244;
				nimln(36, "math.nim");
				T1009420244_9 = mulInt(result0, i_101441_1009420244);
				result0 = (NI)(T1009420244_9);
				nimln(1903, "system.nim");
				T1009420244_10 = addInt(res_101445_1009420244, ((NI) 1));
				res_101445_1009420244 = (NI)(T1009420244_10);
			} LA3: ;
		}
	}
	popFrame();
	return result0;
}

N_NIMCALL(Floatclass101611, classify_101619_1009420244)(NF x0) {
	Floatclass101611 result0;
{	result0 = (Floatclass101611)0;
	{
		if (!(x0 == 0.0)) goto LA3;
		{
			if (!(((NF)(1.0000000000000000e+00) / (NF)(x0)) == INF)) goto LA7;
			result0 = ((Floatclass101611) 2);
			goto BeforeRet;
		}
		goto LA5;
		LA7: ;
		{
			result0 = ((Floatclass101611) 3);
			goto BeforeRet;
		}
		LA5: ;
	}
	LA3: ;
	{
		if (!(((NF)(x0) * (NF)(5.0000000000000000e-01)) == x0)) goto LA12;
		{
			if (!(0.0 < x0)) goto LA16;
			result0 = ((Floatclass101611) 5);
			goto BeforeRet;
		}
		goto LA14;
		LA16: ;
		{
			result0 = ((Floatclass101611) 6);
			goto BeforeRet;
		}
		LA14: ;
	}
	LA12: ;
	{
		if (!!((x0 == x0))) goto LA21;
		result0 = ((Floatclass101611) 4);
		goto BeforeRet;
	}
	LA21: ;
	result0 = ((Floatclass101611) 0);
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NIM_BOOL, ispoweroftwo_101625_1009420244)(NI x0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
{	result0 = (NIM_BOOL)0;
	LOC1 = (NIM_BOOL)0;
	LOC1 = (((NI) 0) < x0);
	if (!(LOC1)) goto LA2;
	LOC1 = ((NI)(x0 & (NI)(x0 - ((NI) 1))) == ((NI) 0));
	LA2: ;
	result0 = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NI, nextpoweroftwo_101629_1009420244)(NI x0) {
	NI result0;
	result0 = (NI)0;
	result0 = (NI)(x0 - ((NI) 1));
	result0 = (NI)(result0 | (NI)((NU64)(result0) >> (NU64)(((NI) 32))));
	result0 = (NI)(result0 | (NI)((NU64)(result0) >> (NU64)(((NI) 16))));
	result0 = (NI)(result0 | (NI)((NU64)(result0) >> (NU64)(((NI) 8))));
	result0 = (NI)(result0 | (NI)((NU64)(result0) >> (NU64)(((NI) 4))));
	result0 = (NI)(result0 | (NI)((NU64)(result0) >> (NU64)(((NI) 2))));
	result0 = (NI)(result0 | (NI)((NU64)(result0) >> (NU64)(((NI) 1))));
	result0 += ((NI) ((NI)(((NI) 1) + ((NI) ((x0 <= ((NI) 0)))))));
	return result0;
}

N_NIMCALL(NI, countbits32_102219_1009420244)(NI32 n0) {
	NI result0;
	NI32 v0;
	result0 = (NI)0;
	v0 = n0;
	v0 = (NI32)((NU32)(v0) - (NU32)((NI32)((NI32)((NU32)(v0) >> (NU32)(((NI32) 1))) & ((NI32) 1431655765))));
	v0 = (NI32)((NU32)((NI32)(v0 & ((NI32) 858993459))) + (NU32)((NI32)((NI32)((NU32)(v0) >> (NU32)(((NI32) 2))) & ((NI32) 858993459))));
	result0 = ((NI) ((NI32)((NU32)((NI32)((NU32)((NI32)((NI32)((NU32)(v0) + (NU32)((NI32)((NU32)(v0) >> (NU32)(((NI32) 4))))) & ((NI32) 252645135))) * (NU32)(((NI32) 16843009)))) >> (NU32)(((NI32) 24)))));
	return result0;
}

N_NIMCALL(NF, round_111661_1009420244)(NF x0, NI places0) {
	NF result0;
	result0 = (NF)0;
	{
		if (!(places0 == ((NI) 0))) goto LA3;
		result0 = round(x0);
	}
	goto LA1;
	LA3: ;
	{
		NF mult0;
		NF LOC6;
		mult0 = pow(1.0000000000000000e+01, ((NF) (places0)));
		LOC6 = (NF)0;
		LOC6 = round(((NF)(x0) * (NF)(mult0)));
		result0 = ((NF)(LOC6) / (NF)(mult0));
	}
	LA1: ;
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void) {
	nimfr("math", "math.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void) {
}

