/* Generated by Nim Compiler v0.15.0 */
/*   (c) 2016 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.15.0/nim/lib -o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/stdlib_sets.o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/stdlib_sets.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, isempty_156229_1431022173)(NI hcode0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21601_1689653243)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, isfilled_156233_1431022173)(NI hcode0);
static N_INLINE(NIM_BOOL, mustrehash_156272_1431022173)(NI length0, NI counter0);
N_NIMCALL(void, failedassertimpl_91639_1689653243)(NimStringDesc* msg0);
N_NIMCALL(NI, mulInt)(NI a0, NI b0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, rightsize_156401_1431022173)(NI count0);
N_NIMCALL(NI, nextpoweroftwo_101629_1009420244)(NI x0);
static N_INLINE(NI, divInt)(NI a0, NI b0);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
static N_INLINE(NI, nexttry_156408_1431022173)(NI h0, NI maxhash0);
STRING_LITERAL(T1431022173_2, "\012  counter < length ", 20);
extern TFrame* frameptr_18836_1689653243;

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18836_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18836_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18836_1689653243;
	frameptr_18836_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21601_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18836_1689653243 = (*frameptr_18836_1689653243).prev;
}

static N_INLINE(NIM_BOOL, isempty_156229_1431022173)(NI hcode0) {
	NIM_BOOL result0;
	nimfr("isEmpty", "sets.nim")
	result0 = (NIM_BOOL)0;
	nimln(47, "sets.nim");
	result0 = (hcode0 == ((NI) 0));
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, isfilled_156233_1431022173)(NI hcode0) {
	NIM_BOOL result0;
	nimfr("isFilled", "sets.nim")
	result0 = (NIM_BOOL)0;
	nimln(50, "sets.nim");
	nimln(347, "system.nim");
	result0 = !((hcode0 == ((NI) 0)));
	popFrame();
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NIM_BOOL, mustrehash_156272_1431022173)(NI length0, NI counter0) {
	NIM_BOOL result0;
	NIM_BOOL LOC5;
	NI T1431022173_3;
	NI T1431022173_4;
	NI T1431022173_5;
	nimfr("mustRehash", "sets.nim")
	result0 = (NIM_BOOL)0;
	nimln(114, "sets.nim");
	{
		if (!!((counter0 < length0))) goto LA3;
		failedassertimpl_91639_1689653243(((NimStringDesc*) &T1431022173_2));
	}
	LA3: ;
	nimln(115, "sets.nim");
	LOC5 = (NIM_BOOL)0;
	T1431022173_3 = mulInt(length0, ((NI) 2));
	T1431022173_4 = mulInt(counter0, ((NI) 3));
	LOC5 = ((NI)(T1431022173_3) < (NI)(T1431022173_4));
	if (LOC5) goto LA6;
	T1431022173_5 = subInt(length0, counter0);
	LOC5 = ((NI)(T1431022173_5) < ((NI) 4));
	LA6: ;
	result0 = LOC5;
	popFrame();
	return result0;
}

static N_INLINE(NI, divInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		if (!(b0 == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (NIM_BOOL)0;
		LOC7 = (a0 == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b0 == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result0 = (NI)(a0 / b0);
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, rightsize_156401_1431022173)(NI count0) {
	NI result0;
	NI T1431022173_6;
	NI T1431022173_7;
	NI T1431022173_8;
	nimfr("rightSize", "sets.nim")
	result0 = (NI)0;
	nimln(124, "sets.nim");
	T1431022173_6 = mulInt(((NI) (count0)), ((NI) 3));
	T1431022173_7 = divInt(((NI) ((NI)(T1431022173_6))), ((NI) 2));
	T1431022173_8 = addInt(((NI) ((NI)(T1431022173_7))), ((NI) 4));
	result0 = nextpoweroftwo_101629_1009420244(((NI) ((NI)(T1431022173_8))));
	popFrame();
	return result0;
}

static N_INLINE(NI, nexttry_156408_1431022173)(NI h0, NI maxhash0) {
	NI result0;
	NI T1431022173_9;
	nimfr("nextTry", "sets.nim")
	result0 = (NI)0;
	nimln(127, "sets.nim");
	T1431022173_9 = addInt(h0, ((NI) 1));
	result0 = (NI)((NI)(T1431022173_9) & maxhash0);
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void) {
	nimfr("sets", "sets.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void) {
}

