/* Generated by Nim Compiler v0.15.0 */
/*   (c) 2016 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.15.0/nim/lib -o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/stdlib_strutils.o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/stdlib_strutils.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Slice91051 Slice91051;
typedef struct Valueerror3646 Valueerror3646;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47705 Cell47705;
typedef struct Cellseq47721 Cellseq47721;
typedef struct Gcheap50218 Gcheap50218;
typedef struct Gcstack50216 Gcstack50216;
typedef struct Memregion29886 Memregion29886;
typedef struct Smallchunk29840 Smallchunk29840;
typedef struct Llchunk29880 Llchunk29880;
typedef struct Bigchunk29842 Bigchunk29842;
typedef struct Intset29814 Intset29814;
typedef struct Trunk29810 Trunk29810;
typedef struct Avlnode29884 Avlnode29884;
typedef struct Gcstat50214 Gcstat50214;
typedef struct Cellset47717 Cellset47717;
typedef struct Pagedesc47713 Pagedesc47713;
typedef struct Basechunk29838 Basechunk29838;
typedef struct Freecell29830 Freecell29830;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Slice91051  {
NI a;
NI b;
};
typedef NU8 Tnimkind3403;
typedef NU8 Tnimtypeflag3409Set;
typedef N_NIMCALL_PTR(void, TY3489) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3403 kind;
Tnimtypeflag3409Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror3646  {
  Exception Sup;
};
typedef NU8 Tnimnodekind3405;
struct  TNimNode  {
Tnimnodekind3405 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell47705  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47721  {
NI len;
NI cap;
Cell47705** d;
};
typedef Smallchunk29840* TY29901[512];
typedef Trunk29810* Trunkbuckets29812[256];
struct  Intset29814  {
Trunkbuckets29812 data;
};
struct  Memregion29886  {
NI minlargeobj;
NI maxlargeobj;
TY29901 freesmallchunks;
Llchunk29880* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29842* freechunkslist;
Intset29814 chunkstarts;
Avlnode29884* root;
Avlnode29884* deleted;
Avlnode29884* last;
Avlnode29884* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat50214  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47717  {
NI counter;
NI max;
Pagedesc47713* head;
Pagedesc47713** data;
};
struct  Gcheap50218  {
Gcstack50216* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47721 zct;
Cellseq47721 decstack;
Cellseq47721 tempstack;
NI recgclock;
Memregion29886 region;
Gcstat50214 stat;
Cellset47717 marked;
Cellseq47721 additionalroots;
};
struct  Gcstack50216  {
Gcstack50216* prev;
Gcstack50216* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk29838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29840  {
  Basechunk29838 Sup;
Smallchunk29840* next;
Smallchunk29840* prev;
Freecell29830* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29880  {
NI size;
NI acc;
Llchunk29880* next;
};
struct  Bigchunk29842  {
  Basechunk29838 Sup;
Bigchunk29842* next;
Bigchunk29842* prev;
NI align;
NF data;
};
typedef NI TY29819[8];
struct  Trunk29810  {
Trunk29810* next;
NI key;
TY29819 bits;
};
typedef Avlnode29884* TY29891[2];
struct  Avlnode29884  {
TY29891 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47713  {
Pagedesc47713* next;
NI key;
TY29819 bits;
};
struct  Freecell29830  {
Freecell29830* next;
NI zerofield;
};
N_NIMCALL(void, reverse_108248_3792311747)(NimStringDesc** a0, NI a0Len0);
N_NIMCALL(void, reverse_108263_3792311747)(NimStringDesc** a0, NI a0Len0, NI first0, NI last0);
static N_INLINE(NIM_BOOL, contains_111475_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0);
static N_INLINE(NI, find_111485_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21601_1689653243)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, contains_111650_1689653243)(Slice91051 s0, NI value0);
N_NIMCALL(NF, round_111661_1009420244)(NF x0, NI places0);
static N_INLINE(void, HEX2AHEX3D_111691_1689653243)(NF* x0, NF y0);
static N_INLINE(void, HEX2BHEX3D_111701_1689653243)(NF* x0, NF y0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x0);
static N_INLINE(void, appendChar)(NimStringDesc* dest0, NIM_CHAR c0);
static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0);
static N_INLINE(void, copymem_7485_1689653243)(void* dest0, void* source0, NI size0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space0);
N_NIMCALL(NimStringDesc*, mnewString)(NI len0);
N_NIMCALL(NimStringDesc*, mnewString)(NI len0);
N_NIMCALL(NI, npuParseInt)(NimStringDesc* s0, NI* number0, NI start0);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell47705*, usrtocell_51840_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_53001_1689653243)(Cell47705* c0);
N_NOINLINE(void, addzct_51817_1689653243)(Cellseq47721* s0, Cell47705* c0);
N_NIMCALL(void, raiseException)(Exception* e0, NCSTRING ename0);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c0);
N_NIMCALL(NIM_CHAR, nsuToUpperAsciiChar)(NIM_CHAR c0);
STRING_LITERAL(T4286263276_4, "invalid integer: ", 17);
extern TFrame* frameptr_18836_1689653243;
extern TNimType NTI23425; /* ref ValueError */
extern TNimType NTI3646; /* ValueError */
extern Gcheap50218 gch_50258_1689653243;

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18836_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18836_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18836_1689653243;
	frameptr_18836_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21601_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18836_1689653243 = (*frameptr_18836_1689653243).prev;
}

static N_INLINE(NI, find_111485_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0) {
	NI result0;
	nimfr("find", "system.nim")
{	result0 = (NI)0;
	{
		NIM_CHAR i_111519_1689653243;
		NI i_111532_1689653243;
		i_111519_1689653243 = (NIM_CHAR)0;
		nimln(1978, "system.nim");
		i_111532_1689653243 = ((NI) 0);
		{
			nimln(1979, "system.nim");
			while (1) {
				NI T4286263276_2;
				NI T4286263276_3;
				if (!(i_111532_1689653243 < a0Len0)) goto LA3;
				nimln(1980, "system.nim");
				if ((NU)(i_111532_1689653243) >= (NU)(a0Len0)) raiseIndexError();
				i_111519_1689653243 = a0[i_111532_1689653243];
				nimln(2203, "system.nim");
				{
					if (!((NU8)(i_111519_1689653243) == (NU8)(item0))) goto LA6;
					goto BeforeRet;
				}
				LA6: ;
				nimln(2204, "system.nim");
				T4286263276_2 = addInt(result0, ((NI) 1));
				result0 = (NI)(T4286263276_2);
				nimln(1981, "system.nim");
				T4286263276_3 = addInt(i_111532_1689653243, ((NI) 1));
				i_111532_1689653243 = (NI)(T4286263276_3);
			} LA3: ;
		}
	}
	nimln(2205, "system.nim");
	result0 = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, contains_111475_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0) {
	NIM_BOOL result0;
	NI LOC1;
	nimfr("contains", "system.nim")
{	result0 = (NIM_BOOL)0;
	nimln(2210, "system.nim");
	nimln(350, "system.nim");
	nimln(351, "system.nim");
	nimln(2210, "system.nim");
	LOC1 = (NI)0;
	LOC1 = find_111485_1689653243(a0, a0Len0, item0);
	result0 = (((NI) 0) <= LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, contains_111650_1689653243)(Slice91051 s0, NI value0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	nimfr("contains", "system.nim")
	result0 = (NIM_BOOL)0;
	nimln(1103, "system.nim");
	LOC1 = (NIM_BOOL)0;
	LOC1 = (((NI) (s0.a)) <= ((NI) (value0)));
	if (!(LOC1)) goto LA2;
	LOC1 = (((NI) (value0)) <= ((NI) (s0.b)));
	LA2: ;
	result0 = LOC1;
	popFrame();
	return result0;
}

static N_INLINE(void, HEX2AHEX3D_111691_1689653243)(NF* x0, NF y0) {
	nimfr("*=", "system.nim")
	nimln(3345, "system.nim");
	(*x0) = ((NF)((*x0)) * (NF)(y0));
	popFrame();
}

static N_INLINE(void, HEX2BHEX3D_111701_1689653243)(NF* x0, NF y0) {
	nimfr("+=", "system.nim")
	nimln(3335, "system.nim");
	(*x0) = ((NF)((*x0)) + (NF)(y0));
	popFrame();
}

static N_INLINE(void, appendChar)(NimStringDesc* dest0, NIM_CHAR c0) {
	(*dest0).data[((*dest0).Sup.len)- 0] = c0;
	(*dest0).data[((NI)((*dest0).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest0).Sup.len += ((NI) 1);
}

static N_INLINE(void, copymem_7485_1689653243)(void* dest0, void* source0, NI size0) {
	void* LOC1;
	LOC1 = (void*)0;
	LOC1 = memcpy(dest0, source0, ((size_t) (size0)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0) {
	copymem_7485_1689653243(((void*) ((&(*dest0).data[((*dest0).Sup.len)- 0]))), ((void*) ((*src0).data)), ((NI) ((NI)((*src0).Sup.len + ((NI) 1)))));
	(*dest0).Sup.len += (*src0).Sup.len;
}

N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x0, NI minchars0) {
	NimStringDesc* result0;
	nimfr("intToStr", "strutils.nim")
	result0 = (NimStringDesc*)0;
	result0 = nimIntToStr((x0 > 0? (x0) : -(x0)));
	{
		NI i_108646_4286263276;
		NI HEX3Atmp_108648_4286263276;
		NI res_108651_4286263276;
		i_108646_4286263276 = (NI)0;
		HEX3Atmp_108648_4286263276 = (NI)0;
		HEX3Atmp_108648_4286263276 = (NI)(((NI) (minchars0)) - (result0 ? result0->Sup.len : 0));
		res_108651_4286263276 = ((NI) 1);
		{
			while (1) {
				NimStringDesc* LOC4;
				if (!(res_108651_4286263276 <= HEX3Atmp_108648_4286263276)) goto LA3;
				i_108646_4286263276 = res_108651_4286263276;
				LOC4 = (NimStringDesc*)0;
				LOC4 = rawNewString(result0->Sup.len + 1);
appendChar(LOC4, 48);
appendString(LOC4, result0);
				result0 = LOC4;
				res_108651_4286263276 += ((NI) 1);
			} LA3: ;
		}
	}
	{
		NimStringDesc* LOC9;
		if (!(x0 < ((NI) 0))) goto LA7;
		LOC9 = (NimStringDesc*)0;
		LOC9 = rawNewString(result0->Sup.len + 1);
appendChar(LOC9, 45);
appendString(LOC9, result0);
		result0 = LOC9;
	}
	LA7: ;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NIM_CHAR c0, NI count0) {
	NimStringDesc* result0;
	nimfr("repeat", "strutils.nim")
	result0 = (NimStringDesc*)0;
	result0 = mnewString(count0);
	{
		NI i_108944_4286263276;
		NI HEX3Atmp_108946_4286263276;
		NI res_108949_4286263276;
		i_108944_4286263276 = (NI)0;
		HEX3Atmp_108946_4286263276 = (NI)0;
		HEX3Atmp_108946_4286263276 = (NI)(((NI) (count0)) - ((NI) 1));
		res_108949_4286263276 = ((NI) 0);
		{
			while (1) {
				if (!(res_108949_4286263276 <= ((NI) (HEX3Atmp_108946_4286263276)))) goto LA3;
				i_108944_4286263276 = ((NI) (res_108949_4286263276));
				result0->data[i_108944_4286263276] = c0;
				res_108949_4286263276 += ((NI) 1);
			} LA3: ;
		}
	}
	popFrame();
	return result0;
}

static N_INLINE(Cell47705*, usrtocell_51840_1689653243)(void* usr0) {
	Cell47705* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell47705*)0;
	nimln(134, "gc.nim");
	result0 = ((Cell47705*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell47705))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_53001_1689653243)(Cell47705* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(214, "gc.nim");
	addzct_51817_1689653243((&gch_50258_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(274, "gc.nim");
	{
		Cell47705* c0;
		nimln(347, "system.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(275, "gc.nim");
		c0 = usrtocell_51840_1689653243(src0);
		nimln(182, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(277, "gc.nim");
	{
		Cell47705* c0;
		nimln(347, "system.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(278, "gc.nim");
		c0 = usrtocell_51840_1689653243((*dest0));
		nimln(279, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c0).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(280, "gc.nim");
			rtladdzct_53001_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(281, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s0) {
	NI result0;
	NI L0;
	nimfr("parseInt", "strutils.nim")
	result0 = (NI)0;
	L0 = npuParseInt(s0, (&result0), ((NI) 0));
	{
		NIM_BOOL LOC3;
		Valueerror3646* e_108664_4286263276;
		NimStringDesc* LOC7;
		LOC3 = (NIM_BOOL)0;
		LOC3 = !((L0 == (s0 ? s0->Sup.len : 0)));
		if (LOC3) goto LA4;
		LOC3 = (L0 == ((NI) 0));
		LA4: ;
		if (!LOC3) goto LA5;
		e_108664_4286263276 = (Valueerror3646*)0;
		e_108664_4286263276 = (Valueerror3646*) newObj((&NTI23425), sizeof(Valueerror3646));
		(*e_108664_4286263276).Sup.Sup.m_type = (&NTI3646);
		LOC7 = (NimStringDesc*)0;
		LOC7 = rawNewString(s0->Sup.len + 17);
appendString(LOC7, ((NimStringDesc*) &T4286263276_4));
appendString(LOC7, s0);
		asgnRefNoCycle((void**) (&(*e_108664_4286263276).Sup.message), LOC7);
		raiseException((Exception*)e_108664_4286263276, "ValueError");
	}
	LA5: ;
	popFrame();
	return result0;
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c0) {
	NIM_CHAR result0;
	nimfr("toLowerAscii", "strutils.nim")
	result0 = (NIM_CHAR)0;
	nimln(207, "strutils.nim");
	{
		NI T4286263276_6;
		nimln(1105, "system.nim");
		if (!(((NU8)(c0)) >= ((NU8)(65)) && ((NU8)(c0)) <= ((NU8)(90)))) goto LA3;
		nimln(208, "strutils.nim");
		T4286263276_6 = addInt(((NI) (((NU8)(c0)))), ((NI) 32));
		result0 = ((NIM_CHAR) (((NI)chckRange((NI)(T4286263276_6), ((NI) 0), ((NI) 255)))));
	}
	goto LA1;
	LA3: ;
	{
		nimln(210, "strutils.nim");
		result0 = c0;
	}
	LA1: ;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, nsuToLowerAsciiStr)(NimStringDesc* s0) {
	NimStringDesc* result0;
	nimfr("toLowerAscii", "strutils.nim")
	result0 = (NimStringDesc*)0;
	nimln(219, "strutils.nim");
	result0 = mnewString(((NI)chckRange((s0 ? s0->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i_106845_4286263276;
		NI HEX3Atmp_106847_4286263276;
		NI T4286263276_5;
		NI res_106850_4286263276;
		i_106845_4286263276 = (NI)0;
		HEX3Atmp_106847_4286263276 = (NI)0;
		nimln(220, "strutils.nim");
		T4286263276_5 = subInt((s0 ? s0->Sup.len : 0), ((NI) 1));
		HEX3Atmp_106847_4286263276 = (NI)(T4286263276_5);
		nimln(1887, "system.nim");
		res_106850_4286263276 = ((NI) 0);
		{
			nimln(1888, "system.nim");
			while (1) {
				NI T4286263276_7;
				if (!(res_106850_4286263276 <= HEX3Atmp_106847_4286263276)) goto LA3;
				nimln(1889, "system.nim");
				i_106845_4286263276 = res_106850_4286263276;
				nimln(221, "strutils.nim");
				if ((NU)(i_106845_4286263276) > (NU)(result0->Sup.len)) raiseIndexError();
				if ((NU)(i_106845_4286263276) > (NU)(s0->Sup.len)) raiseIndexError();
				result0->data[i_106845_4286263276] = nsuToLowerAsciiChar(s0->data[i_106845_4286263276]);
				nimln(1908, "system.nim");
				T4286263276_7 = addInt(res_106850_4286263276, ((NI) 1));
				res_106850_4286263276 = (NI)(T4286263276_7);
			} LA3: ;
		}
	}
	popFrame();
	return result0;
}

N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a0, NimStringDesc* b0) {
	NI result0;
	NI i0;
	NI m0;
	NI T4286263276_10;
	nimfr("cmpIgnoreCase", "strutils.nim")
{	result0 = (NI)0;
	nimln(408, "strutils.nim");
	i0 = ((NI) 0);
	nimln(409, "strutils.nim");
	m0 = (((a0 ? a0->Sup.len : 0) <= (b0 ? b0->Sup.len : 0)) ? (a0 ? a0->Sup.len : 0) : (b0 ? b0->Sup.len : 0));
	{
		nimln(410, "strutils.nim");
		while (1) {
			NIM_CHAR LOC3;
			NIM_CHAR LOC4;
			NI T4286263276_8;
			NI T4286263276_9;
			if (!(i0 < m0)) goto LA2;
			nimln(411, "strutils.nim");
			if ((NU)(i0) > (NU)(a0->Sup.len)) raiseIndexError();
			LOC3 = (NIM_CHAR)0;
			LOC3 = nsuToLowerAsciiChar(a0->data[i0]);
			if ((NU)(i0) > (NU)(b0->Sup.len)) raiseIndexError();
			LOC4 = (NIM_CHAR)0;
			LOC4 = nsuToLowerAsciiChar(b0->data[i0]);
			T4286263276_8 = subInt(((NI) (((NU8)(LOC3)))), ((NI) (((NU8)(LOC4)))));
			result0 = (NI)(T4286263276_8);
			nimln(412, "strutils.nim");
			{
				nimln(347, "system.nim");
				if (!!((result0 == ((NI) 0)))) goto LA7;
				nimln(412, "strutils.nim");
				goto BeforeRet;
			}
			LA7: ;
			nimln(413, "strutils.nim");
			T4286263276_9 = addInt(i0, ((NI) 1));
			i0 = (NI)(T4286263276_9);
		} LA2: ;
	}
	nimln(414, "strutils.nim");
	T4286263276_10 = subInt((a0 ? a0->Sup.len : 0), (b0 ? b0->Sup.len : 0));
	result0 = (NI)(T4286263276_10);
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_CHAR, nsuToUpperAsciiChar)(NIM_CHAR c0) {
	NIM_CHAR result0;
	nimfr("toUpperAscii", "strutils.nim")
	result0 = (NIM_CHAR)0;
	nimln(230, "strutils.nim");
	{
		NI T4286263276_12;
		nimln(1105, "system.nim");
		if (!(((NU8)(c0)) >= ((NU8)(97)) && ((NU8)(c0)) <= ((NU8)(122)))) goto LA3;
		nimln(231, "strutils.nim");
		T4286263276_12 = subInt(((NI) (((NU8)(c0)))), ((NI) 32));
		result0 = ((NIM_CHAR) (((NI)chckRange((NI)(T4286263276_12), ((NI) 0), ((NI) 255)))));
	}
	goto LA1;
	LA3: ;
	{
		nimln(233, "strutils.nim");
		result0 = c0;
	}
	LA1: ;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, nsuToUpperAsciiStr)(NimStringDesc* s0) {
	NimStringDesc* result0;
	nimfr("toUpperAscii", "strutils.nim")
	result0 = (NimStringDesc*)0;
	nimln(242, "strutils.nim");
	result0 = mnewString(((NI)chckRange((s0 ? s0->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i_106909_4286263276;
		NI HEX3Atmp_106911_4286263276;
		NI T4286263276_11;
		NI res_106914_4286263276;
		i_106909_4286263276 = (NI)0;
		HEX3Atmp_106911_4286263276 = (NI)0;
		nimln(243, "strutils.nim");
		T4286263276_11 = subInt((s0 ? s0->Sup.len : 0), ((NI) 1));
		HEX3Atmp_106911_4286263276 = (NI)(T4286263276_11);
		nimln(1887, "system.nim");
		res_106914_4286263276 = ((NI) 0);
		{
			nimln(1888, "system.nim");
			while (1) {
				NI T4286263276_13;
				if (!(res_106914_4286263276 <= HEX3Atmp_106911_4286263276)) goto LA3;
				nimln(1889, "system.nim");
				i_106909_4286263276 = res_106914_4286263276;
				nimln(244, "strutils.nim");
				if ((NU)(i_106909_4286263276) > (NU)(result0->Sup.len)) raiseIndexError();
				if ((NU)(i_106909_4286263276) > (NU)(s0->Sup.len)) raiseIndexError();
				result0->data[i_106909_4286263276] = nsuToUpperAsciiChar(s0->data[i_106909_4286263276]);
				nimln(1908, "system.nim");
				T4286263276_13 = addInt(res_106914_4286263276, ((NI) 1));
				res_106914_4286263276 = (NI)(T4286263276_13);
			} LA3: ;
		}
	}
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void) {
	nimfr("strutils", "strutils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void) {
}

