/* Generated by Nim Compiler v0.15.0 */
/*   (c) 2016 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.15.0/nim/lib -o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/stdlib_parseutils.o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/stdlib_parseutils.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Overflowerror3640 Overflowerror3640;
typedef struct Arithmeticerror3636 Arithmeticerror3636;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47705 Cell47705;
typedef struct Cellseq47721 Cellseq47721;
typedef struct Gcheap50218 Gcheap50218;
typedef struct Gcstack50216 Gcstack50216;
typedef struct Memregion29886 Memregion29886;
typedef struct Smallchunk29840 Smallchunk29840;
typedef struct Llchunk29880 Llchunk29880;
typedef struct Bigchunk29842 Bigchunk29842;
typedef struct Intset29814 Intset29814;
typedef struct Trunk29810 Trunk29810;
typedef struct Avlnode29884 Avlnode29884;
typedef struct Gcstat50214 Gcstat50214;
typedef struct Cellset47717 Cellset47717;
typedef struct Pagedesc47713 Pagedesc47713;
typedef struct Basechunk29838 Basechunk29838;
typedef struct Freecell29830 Freecell29830;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 Tnimkind3403;
typedef NU8 Tnimtypeflag3409Set;
typedef N_NIMCALL_PTR(void, TY3489) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3403 kind;
Tnimtypeflag3409Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Arithmeticerror3636  {
  Exception Sup;
};
struct  Overflowerror3640  {
  Arithmeticerror3636 Sup;
};
typedef NU8 Tnimnodekind3405;
struct  TNimNode  {
Tnimnodekind3405 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell47705  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47721  {
NI len;
NI cap;
Cell47705** d;
};
typedef Smallchunk29840* TY29901[512];
typedef Trunk29810* Trunkbuckets29812[256];
struct  Intset29814  {
Trunkbuckets29812 data;
};
struct  Memregion29886  {
NI minlargeobj;
NI maxlargeobj;
TY29901 freesmallchunks;
Llchunk29880* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29842* freechunkslist;
Intset29814 chunkstarts;
Avlnode29884* root;
Avlnode29884* deleted;
Avlnode29884* last;
Avlnode29884* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat50214  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47717  {
NI counter;
NI max;
Pagedesc47713* head;
Pagedesc47713** data;
};
struct  Gcheap50218  {
Gcstack50216* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47721 zct;
Cellseq47721 decstack;
Cellseq47721 tempstack;
NI recgclock;
Memregion29886 region;
Gcstat50214 stat;
Cellset47717 marked;
Cellseq47721 additionalroots;
};
struct  Gcstack50216  {
Gcstack50216* prev;
Gcstack50216* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk29838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29840  {
  Basechunk29838 Sup;
Smallchunk29840* next;
Smallchunk29840* prev;
Freecell29830* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29880  {
NI size;
NI acc;
Llchunk29880* next;
};
struct  Bigchunk29842  {
  Basechunk29838 Sup;
Bigchunk29842* next;
Bigchunk29842* prev;
NI align;
NF data;
};
typedef NI TY29819[8];
struct  Trunk29810  {
Trunk29810* next;
NI key;
TY29819 bits;
};
typedef Avlnode29884* TY29891[2];
struct  Avlnode29884  {
TY29891 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47713  {
Pagedesc47713* next;
NI key;
TY29819 bits;
};
struct  Freecell29830  {
Freecell29830* next;
NI zerofield;
};
N_NIMCALL(NI, npuParseBiggestInt)(NimStringDesc* s0, NI64* number0, NI start0);
N_NIMCALL(NI, rawparseint_98357_1912046442)(NimStringDesc* s0, NI64* b0, NI start0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI64, mulInt64)(NI64 a0, NI64 b0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
static N_INLINE(NI64, subInt64)(NI64 a0, NI64 b0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21601_1689653243)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p0);
static N_INLINE(Cell47705*, usrtocell_51840_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_53001_1689653243)(Cell47705* c0);
N_NOINLINE(void, addzct_51817_1689653243)(Cellseq47721* s0, Cell47705* c0);
N_NIMCALL(void, raiseException)(Exception* e0, NCSTRING ename0);
STRING_LITERAL(T1912046442_11, "overflow", 8);
extern TFrame* frameptr_18836_1689653243;
extern TNimType NTI23671; /* ref OverflowError */
extern TNimType NTI3640; /* OverflowError */
extern Gcheap50218 gch_50258_1689653243;

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI64, subInt64)(NI64 a0, NI64 b0) {
	NI64 result0;
{	result0 = (NI64)0;
	result0 = (NI64)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (IL64(0) <= (NI64)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (IL64(0) <= (NI64)(result0 ^ (NI64)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18836_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18836_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18836_1689653243;
	frameptr_18836_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21601_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18836_1689653243 = (*frameptr_18836_1689653243).prev;
}

N_NIMCALL(NI, rawparseint_98357_1912046442)(NimStringDesc* s0, NI64* b0, NI start0) {
	NI result0;
	NI64 sign0;
	NI i0;
	nimfr("rawParseInt", "parseutils.nim")
	result0 = (NI)0;
	nimln(213, "parseutils.nim");
	sign0 = IL64(-1);
	nimln(214, "parseutils.nim");
	i0 = start0;
	nimln(215, "parseutils.nim");
	{
		NI T1912046442_2;
		if ((NU)(i0) > (NU)(s0->Sup.len)) raiseIndexError();
		if (!((NU8)(s0->data[i0]) == (NU8)(43))) goto LA3;
		T1912046442_2 = addInt(i0, ((NI) 1));
		i0 = (NI)(T1912046442_2);
	}
	goto LA1;
	LA3: ;
	{
		NI T1912046442_3;
		nimln(216, "parseutils.nim");
		if ((NU)(i0) > (NU)(s0->Sup.len)) raiseIndexError();
		if (!((NU8)(s0->data[i0]) == (NU8)(45))) goto LA6;
		nimln(217, "parseutils.nim");
		T1912046442_3 = addInt(i0, ((NI) 1));
		i0 = (NI)(T1912046442_3);
		nimln(218, "parseutils.nim");
		sign0 = IL64(1);
	}
	goto LA1;
	LA6: ;
	LA1: ;
	nimln(219, "parseutils.nim");
	{
		NI64 T1912046442_9;
		NI T1912046442_10;
		nimln(1105, "system.nim");
		if ((NU)(i0) > (NU)(s0->Sup.len)) raiseIndexError();
		if (!(((NU8)(s0->data[i0])) >= ((NU8)(48)) && ((NU8)(s0->data[i0])) <= ((NU8)(57)))) goto LA10;
		nimln(220, "parseutils.nim");
		(*b0) = IL64(0);
		{
			nimln(221, "parseutils.nim");
			while (1) {
				NI64 T1912046442_4;
				NI T1912046442_5;
				NI64 T1912046442_6;
				NI T1912046442_7;
				nimln(1105, "system.nim");
				if ((NU)(i0) > (NU)(s0->Sup.len)) raiseIndexError();
				if (!(((NU8)(s0->data[i0])) >= ((NU8)(48)) && ((NU8)(s0->data[i0])) <= ((NU8)(57)))) goto LA13;
				nimln(222, "parseutils.nim");
				T1912046442_4 = mulInt64((*b0), IL64(10));
				if ((NU)(i0) > (NU)(s0->Sup.len)) raiseIndexError();
				T1912046442_5 = subInt(((NI) (((NU8)(s0->data[i0])))), ((NI) 48));
				T1912046442_6 = subInt64((NI64)(T1912046442_4), ((NI64) ((NI)(T1912046442_5))));
				(*b0) = (NI64)(T1912046442_6);
				nimln(223, "parseutils.nim");
				T1912046442_7 = addInt(i0, ((NI) 1));
				i0 = (NI)(T1912046442_7);
				{
					nimln(224, "parseutils.nim");
					while (1) {
						NI T1912046442_8;
						if ((NU)(i0) > (NU)(s0->Sup.len)) raiseIndexError();
						if (!((NU8)(s0->data[i0]) == (NU8)(95))) goto LA15;
						T1912046442_8 = addInt(i0, ((NI) 1));
						i0 = (NI)(T1912046442_8);
					} LA15: ;
				}
			} LA13: ;
		}
		nimln(225, "parseutils.nim");
		T1912046442_9 = mulInt64((*b0), sign0);
		(*b0) = (NI64)(T1912046442_9);
		nimln(226, "parseutils.nim");
		T1912046442_10 = subInt(i0, start0);
		result0 = (NI)(T1912046442_10);
	}
	LA10: ;
	popFrame();
	return result0;
}

N_NIMCALL(NI, npuParseBiggestInt)(NimStringDesc* s0, NI64* number0, NI start0) {
	NI result0;
	NI64 res0;
	nimfr("parseBiggestInt", "parseutils.nim")
	result0 = (NI)0;
	res0 = (NI64)0;
	nimln(237, "parseutils.nim");
	result0 = rawparseint_98357_1912046442(s0, (&res0), start0);
	nimln(238, "parseutils.nim");
	(*number0) = res0;
	popFrame();
	return result0;
}

static N_INLINE(Cell47705*, usrtocell_51840_1689653243)(void* usr0) {
	Cell47705* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell47705*)0;
	nimln(134, "gc.nim");
	result0 = ((Cell47705*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell47705))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_53001_1689653243)(Cell47705* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(214, "gc.nim");
	addzct_51817_1689653243((&gch_50258_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p0) {
	Cell47705* c0;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(256, "gc.nim");
	c0 = usrtocell_51840_1689653243(p0);
	nimln(258, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c0).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(259, "gc.nim");
		rtladdzct_53001_1689653243(c0);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(NI, npuParseInt)(NimStringDesc* s0, NI* number0, NI start0) {
	NI result0;
	NI64 res0;
	nimfr("parseInt", "parseutils.nim")
	result0 = (NI)0;
	res0 = (NI64)0;
	nimln(246, "parseutils.nim");
	result0 = npuParseBiggestInt(s0, (&res0), start0);
	nimln(247, "parseutils.nim");
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC5;
		Overflowerror3640* e_98471_1912046442;
		NimStringDesc* LOC9;
		LOC3 = (NIM_BOOL)0;
		LOC3 = NIM_FALSE;
		if (!(LOC3)) goto LA4;
		nimln(248, "parseutils.nim");
		LOC5 = (NIM_BOOL)0;
		LOC5 = (res0 < (IL64(-9223372036854775807) - IL64(1)));
		if (LOC5) goto LA6;
		nimln(355, "system.nim");
		LOC5 = (IL64(9223372036854775807) < res0);
		LA6: ;
		LOC3 = LOC5;
		LA4: ;
		if (!LOC3) goto LA7;
		e_98471_1912046442 = (Overflowerror3640*)0;
		nimln(2526, "system.nim");
		e_98471_1912046442 = (Overflowerror3640*) newObj((&NTI23671), sizeof(Overflowerror3640));
		(*e_98471_1912046442).Sup.Sup.Sup.m_type = (&NTI3640);
		nimln(2527, "system.nim");
		LOC9 = (NimStringDesc*)0;
		LOC9 = (*e_98471_1912046442).Sup.Sup.message; (*e_98471_1912046442).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &T1912046442_11));
		if (LOC9) nimGCunrefNoCycle(LOC9);
		nimln(249, "parseutils.nim");
		raiseException((Exception*)e_98471_1912046442, "OverflowError");
	}
	goto LA1;
	LA7: ;
	{
		nimln(347, "system.nim");
		if (!!((result0 == ((NI) 0)))) goto LA11;
		nimln(251, "parseutils.nim");
		(*number0) = ((NI) (res0));
	}
	goto LA1;
	LA11: ;
	LA1: ;
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void) {
	nimfr("parseutils", "parseutils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void) {
}

