/* Generated by Nim Compiler v0.15.0 */
/*   (c) 2016 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.15.0/nim/lib -o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/stdlib_nativesockets.o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/stdlib_nativesockets.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <netdb.h>
#include <string.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <sys/select.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Servent147610 Servent147610;
typedef struct TY15205 TY15205;
typedef struct Hostent147612 Hostent147612;
typedef struct TY151012 TY151012;
typedef struct TY152035 TY152035;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NU8 Domain147604;
typedef NU8 Socktype147606;
typedef NU8 Protocol147608;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Servent147610  {
NimStringDesc* name;
TY15205* aliases;
NU16 port;
NimStringDesc* proto;
};
struct  Hostent147612  {
NimStringDesc* name;
TY15205* aliases;
Domain147604 addrtype;
NI length;
TY15205* addrlist;
};
typedef NIM_CHAR TY121654[256];
typedef NIM_CHAR TY121684[16];
struct TY151012 {
NimStringDesc* Field0;
NU16 Field1;
};
typedef NIM_CHAR TY151406[64];
typedef NU8 Tnimkind3403;
typedef NU8 Tnimtypeflag3409Set;
typedef N_NIMCALL_PTR(void, TY3489) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3403 kind;
Tnimtypeflag3409Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
typedef NU8 Tnimnodekind3405;
struct  TNimNode  {
Tnimnodekind3405 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY15205 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY152035 {
  TGenericSeq Sup;
  int data[SEQ_DECL_SIZE];
};
N_NIMCALL(int, toint_147820_466562973)(Domain147604 domain0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21601_1689653243)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(int, toint_147823_466562973)(Socktype147606 typ0);
N_NIMCALL(int, toint_147826_466562973)(Protocol147608 p0);
N_NIMCALL(int, newnativesocket_148001_466562973)(Domain147604 domain0, Socktype147606 socktype0, Protocol147608 protocol0);
N_NIMCALL(int, newnativesocket_148007_466562973)(int domain0, int socktype0, int protocol0);
N_NIMCALL(void, close_148013_466562973)(int socket0);
N_NIMCALL(int, bindaddr_148208_466562973)(int socket0, struct sockaddr* name0, socklen_t namelen0);
N_NIMCALL(int, listen_148215_466562973)(int socket0, int backlog0);
N_NIMCALL(struct addrinfo*, getaddrinfo_148402_466562973)(NimStringDesc* address0, NU16 port0, Domain147604 domain0, Socktype147606 socktype0, Protocol147608 protocol0);
N_NIMCALL(NimStringDesc*, HEX24_8401_1689653243)(NU64 x0);
N_NOINLINE(void, raiseoserror_130603_2125978480)(NI32 errorcode0, NimStringDesc* additionalinfo0);
N_NIMCALL(NI32, oslasterror_130619_2125978480)(void);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str0);
N_NIMCALL(void, dealloc_148802_466562973)(struct addrinfo* ai0);
N_NIMCALL(NU32, ntohl_148806_466562973)(NU32 x0);
N_NIMCALL(NU16, ntohs_149088_466562973)(NU16 x0);
N_NIMCALL(void, getservbyname_149250_466562973)(NimStringDesc* name0, NimStringDesc* proto0, Servent147610* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest0, void* src0);
N_NIMCALL(TY15205*, cstringarraytoseq_15422_1689653243)(NCSTRING* a0);
N_NIMCALL(void, getservbyport_149414_466562973)(NU16 port0, NimStringDesc* proto0, Servent147610* Result);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
N_NIMCALL(void, gethostbyaddr_149614_466562973)(NimStringDesc* ip0, Hostent147612* Result);
N_NIMCALL(void, gethostbyname_150204_466562973)(NimStringDesc* name0, Hostent147612* Result);
N_NIMCALL(Domain147604, getsockdomain_150602_466562973)(int socket0);
N_NIMCALL(NimStringDesc*, getaddrstring_150613_466562973)(struct sockaddr* sockaddr0);
N_NIMCALL(NimStringDesc*, mnewString)(NI len0);
N_NIMCALL(NimStringDesc*, mnewString)(NI len0);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s0, NI start0);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s0, NI first0);
N_NIMCALL(NU16, getsockname_150806_466562973)(int socket0);
N_NIMCALL(void, getlocaladdr_151008_466562973)(int socket0, Domain147604 domain0, TY151012* Result);
N_NIMCALL(void, getpeeraddr_151419_466562973)(int socket0, Domain147604 domain0, TY151012* Result);
N_NIMCALL(NI, getsockoptint_151819_466562973)(int socket0, NI level0, NI optname0);
N_NIMCALL(void, setsockoptint_151831_466562973)(int socket0, NI level0, NI optname0, NI optval0);
N_NIMCALL(void, setblocking_151839_466562973)(int s0, NIM_BOOL blocking0);
N_NIMCALL(struct timeval, timevalfrommilliseconds_152022_466562973)(NI timeout0);
static N_INLINE(NI, divInt)(NI a0, NI b0);
N_NOINLINE(void, raiseDivByZero)(void);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, mulInt)(NI a0, NI b0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NIMCALL(void, createfdset_152031_466562973)(fd_set* fd0, TY152035* s0, NI* m0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NIMCALL(void, failedassertimpl_91639_1689653243)(NimStringDesc* msg0);
N_NIMCALL(void, prunesocketset_152222_466562973)(TY152035** s0, fd_set* fd0);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq0, NI elemsize0, NI newlen0);
N_NIMCALL(NI, select_152277_466562973)(TY152035** readfds0, NI timeout0);
N_NIMCALL(NI, selectwrite_152328_466562973)(TY152035** writefds0, NI timeout0);
STRING_LITERAL(T466562973_2, "Service not found.", 18);
STRING_LITERAL(T466562973_3, "unknown h_addrtype", 18);
STRING_LITERAL(T466562973_4, "", 0);
STRING_LITERAL(T466562973_5, "unknown socket family in getSockFamily", 38);
STRING_LITERAL(T466562973_6, "unknown socket family in getAddrString", 38);
STRING_LITERAL(T466562973_7, "invalid socket family in getLocalAddr", 37);
STRING_LITERAL(T466562973_13, "len(a) == L seq modified while iterating over it", 48);
int osinvalidsocket_147651_466562973;
int nativeafinet_147652_466562973;
int nativeafinet6_147653_466562973;
extern TFrame* frameptr_18836_1689653243;
TNimType NTI147604; /* Domain */
TNimType NTI147606; /* SockType */
TNimType NTI147608; /* Protocol */

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18836_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18836_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18836_1689653243;
	frameptr_18836_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21601_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18836_1689653243 = (*frameptr_18836_1689653243).prev;
}

N_NIMCALL(int, toint_147820_466562973)(Domain147604 domain0) {
	int result0;
	nimfr("toInt", "nativesockets.nim")
	result0 = (int)0;
	nimln(125, "nativesockets.nim");
	switch (domain0) {
	case ((Domain147604) 0):
	{
		nimln(126, "nativesockets.nim");
		result0 = AF_UNIX;
	}
	break;
	case ((Domain147604) 2):
	{
		nimln(127, "nativesockets.nim");
		result0 = AF_INET;
	}
	break;
	case ((Domain147604) 23):
	{
		nimln(128, "nativesockets.nim");
		result0 = AF_INET6;
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result0;
}

N_NIMCALL(int, toint_147823_466562973)(Socktype147606 typ0) {
	int result0;
	nimfr("toInt", "nativesockets.nim")
	result0 = (int)0;
	nimln(132, "nativesockets.nim");
	switch (typ0) {
	case ((Socktype147606) 1):
	{
		nimln(133, "nativesockets.nim");
		result0 = SOCK_STREAM;
	}
	break;
	case ((Socktype147606) 2):
	{
		nimln(134, "nativesockets.nim");
		result0 = SOCK_DGRAM;
	}
	break;
	case ((Socktype147606) 5):
	{
		nimln(135, "nativesockets.nim");
		result0 = SOCK_SEQPACKET;
	}
	break;
	case ((Socktype147606) 3):
	{
		nimln(136, "nativesockets.nim");
		result0 = SOCK_RAW;
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result0;
}

N_NIMCALL(int, toint_147826_466562973)(Protocol147608 p0) {
	int result0;
	nimfr("toInt", "nativesockets.nim")
	result0 = (int)0;
	nimln(140, "nativesockets.nim");
	switch (p0) {
	case ((Protocol147608) 6):
	{
		nimln(141, "nativesockets.nim");
		result0 = IPPROTO_TCP;
	}
	break;
	case ((Protocol147608) 17):
	{
		nimln(142, "nativesockets.nim");
		result0 = IPPROTO_UDP;
	}
	break;
	case ((Protocol147608) 18):
	{
		nimln(143, "nativesockets.nim");
		result0 = IPPROTO_IP;
	}
	break;
	case ((Protocol147608) 19):
	{
		nimln(144, "nativesockets.nim");
		result0 = IPPROTO_IPV6;
	}
	break;
	case ((Protocol147608) 20):
	{
		nimln(145, "nativesockets.nim");
		result0 = IPPROTO_RAW;
	}
	break;
	case ((Protocol147608) 21):
	{
		nimln(146, "nativesockets.nim");
		result0 = IPPROTO_ICMP;
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result0;
}

N_NIMCALL(int, newnativesocket_148001_466562973)(Domain147604 domain0, Socktype147606 socktype0, Protocol147608 protocol0) {
	int result0;
	int LOC1;
	int LOC2;
	int LOC3;
	nimfr("newNativeSocket", "nativesockets.nim")
	result0 = (int)0;
	nimln(163, "nativesockets.nim");
	nimln(164, "nativesockets.nim");
	LOC1 = (int)0;
	LOC1 = toint_147820_466562973(domain0);
	LOC2 = (int)0;
	LOC2 = toint_147823_466562973(socktype0);
	LOC3 = (int)0;
	LOC3 = toint_147826_466562973(protocol0);
	result0 = socket(LOC1, LOC2, LOC3);
	popFrame();
	return result0;
}

N_NIMCALL(int, newnativesocket_148007_466562973)(int domain0, int socktype0, int protocol0) {
	int result0;
	nimfr("newNativeSocket", "nativesockets.nim")
	result0 = (int)0;
	nimln(168, "nativesockets.nim");
	nimln(172, "nativesockets.nim");
	result0 = socket(domain0, socktype0, protocol0);
	popFrame();
	return result0;
}

N_NIMCALL(void, close_148013_466562973)(int socket0) {
	int LOC1;
	nimfr("close", "nativesockets.nim")
	nimln(179, "nativesockets.nim");
	LOC1 = (int)0;
	LOC1 = close(socket0);
	popFrame();
}

N_NIMCALL(int, bindaddr_148208_466562973)(int socket0, struct sockaddr* name0, socklen_t namelen0) {
	int result0;
	nimfr("bindAddr", "nativesockets.nim")
	result0 = (int)0;
	nimln(184, "nativesockets.nim");
	result0 = bind(socket0, name0, namelen0);
	popFrame();
	return result0;
}

N_NIMCALL(int, listen_148215_466562973)(int socket0, int backlog0) {
	int result0;
	nimfr("listen", "nativesockets.nim")
	result0 = (int)0;
	nimln(193, "nativesockets.nim");
	result0 = listen(socket0, backlog0);
	popFrame();
	return result0;
}

N_NIMCALL(struct addrinfo*, getaddrinfo_148402_466562973)(NimStringDesc* address0, NU16 port0, Domain147604 domain0, Socktype147606 socktype0, Protocol147608 protocol0) {
	struct addrinfo* result0;
	struct addrinfo hints0;
	int gairesult0;
	NimStringDesc* LOC5;
	nimfr("getAddrInfo", "nativesockets.nim")
	result0 = (struct addrinfo*)0;
	memset((void*)(&hints0), 0, sizeof(hints0));
	nimln(202, "nativesockets.nim");
	result0 = NIM_NIL;
	nimln(203, "nativesockets.nim");
	hints0.ai_family = toint_147820_466562973(domain0);
	nimln(204, "nativesockets.nim");
	hints0.ai_socktype = toint_147823_466562973(socktype0);
	nimln(205, "nativesockets.nim");
	hints0.ai_protocol = toint_147826_466562973(protocol0);
	nimln(210, "nativesockets.nim");
	{
		if (!(domain0 == ((Domain147604) 23))) goto LA3;
		nimln(211, "nativesockets.nim");
		hints0.ai_flags = AI_V4MAPPED;
	}
	LA3: ;
	nimln(212, "nativesockets.nim");
	LOC5 = (NimStringDesc*)0;
	LOC5 = HEX24_8401_1689653243(port0);
	gairesult0 = getaddrinfo(address0->data, LOC5->data, (&hints0), &result0);
	nimln(213, "nativesockets.nim");
	{
		NI32 LOC10;
		NCSTRING LOC11;
		NimStringDesc* LOC12;
		nimln(347, "system.nim");
		if (!!((gairesult0 == ((NI32) 0)))) goto LA8;
		nimln(217, "nativesockets.nim");
		LOC10 = (NI32)0;
		LOC10 = oslasterror_130619_2125978480();
		LOC11 = (NCSTRING)0;
		LOC11 = (char *)gai_strerror(gairesult0);
		LOC12 = (NimStringDesc*)0;
		LOC12 = cstrToNimstr(LOC11);
		raiseoserror_130603_2125978480(LOC10, LOC12);
	}
	LA8: ;
	popFrame();
	return result0;
}

N_NIMCALL(void, dealloc_148802_466562973)(struct addrinfo* ai0) {
	nimfr("dealloc", "nativesockets.nim")
	nimln(220, "nativesockets.nim");
	freeaddrinfo(ai0);
	popFrame();
}

N_NIMCALL(NU32, ntohl_148806_466562973)(NU32 x0) {
	NU32 result0;
	nimfr("ntohl", "nativesockets.nim")
	result0 = (NU32)0;
	nimln(227, "nativesockets.nim");
	nimln(229, "nativesockets.nim");
	nimln(228, "nativesockets.nim");
	nimln(227, "nativesockets.nim");
	nimln(228, "nativesockets.nim");
	nimln(229, "nativesockets.nim");
	nimln(230, "nativesockets.nim");
	result0 = (NU32)((NU32)((NU32)((NU32)((NU32)(x0) >> (NU32)(((NU32) 24))) | (NU32)((NU32)((NU32)(x0) >> (NU32)(((NU32) 8))) & ((NU32) 65280))) | (NU32)((NU32)((NU32)(x0) << (NU32)(((NU32) 8))) & ((NU32) 16711680))) | (NU32)((NU32)(x0) << (NU32)(((NU32) 24))));
	popFrame();
	return result0;
}

N_NIMCALL(NU16, ntohs_149088_466562973)(NU16 x0) {
	NU16 result0;
	nimfr("ntohs", "nativesockets.nim")
	result0 = (NU16)0;
	nimln(246, "nativesockets.nim");
	result0 = (NU16)((NU16)((NU16)(x0) >> (NU16)(((NU16) 8))) | (NU16)((NU16)(x0) << (NU16)(((NU16) 8))));
	popFrame();
	return result0;
}

N_NIMCALL(void, getservbyname_149250_466562973)(NimStringDesc* name0, NimStringDesc* proto0, Servent147610* Result) {
	struct servent* s0;
	nimfr("getServByName", "nativesockets.nim")
	nimln(296, "nativesockets.nim");
	s0 = getservbyname(name0->data, proto0->data);
	nimln(297, "nativesockets.nim");
	{
		NI32 LOC5;
		if (!(s0 == NIM_NIL)) goto LA3;
		LOC5 = (NI32)0;
		LOC5 = oslasterror_130619_2125978480();
		raiseoserror_130603_2125978480(LOC5, ((NimStringDesc*) &T466562973_2));
	}
	LA3: ;
	nimln(298, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s0).s_name));
	nimln(299, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringarraytoseq_15422_1689653243((*s0).s_aliases));
	nimln(300, "nativesockets.nim");
	(*Result).port = ((NU16) ((*s0).s_port));
	nimln(301, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).proto), cstrToNimstr((*s0).s_proto));
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, getservbyport_149414_466562973)(NU16 port0, NimStringDesc* proto0, Servent147610* Result) {
	struct servent* s0;
	nimfr("getServByPort", "nativesockets.nim")
	nimln(312, "nativesockets.nim");
	s0 = getservbyport(((int)chckRange(((NI)(NU)(NU16)(((NI16)chckRange(port0, ((NI16) -32768), ((NI16) 32767))))), ((int) (-2147483647 -1)), ((int) 2147483647))), proto0->data);
	nimln(313, "nativesockets.nim");
	{
		NI32 LOC5;
		if (!(s0 == NIM_NIL)) goto LA3;
		LOC5 = (NI32)0;
		LOC5 = oslasterror_130619_2125978480();
		raiseoserror_130603_2125978480(LOC5, ((NimStringDesc*) &T466562973_2));
	}
	LA3: ;
	nimln(314, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s0).s_name));
	nimln(315, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringarraytoseq_15422_1689653243((*s0).s_aliases));
	nimln(316, "nativesockets.nim");
	(*Result).port = ((NU16) ((*s0).s_port));
	nimln(317, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).proto), cstrToNimstr((*s0).s_proto));
	popFrame();
}

N_NIMCALL(void, gethostbyaddr_149614_466562973)(NimStringDesc* ip0, Hostent147612* Result) {
	struct in_addr myaddr0;
	struct hostent* s0;
	nimfr("getHostByAddr", "nativesockets.nim")
	memset((void*)(&myaddr0), 0, sizeof(myaddr0));
	nimln(322, "nativesockets.nim");
	myaddr0.s_addr = inet_addr(ip0->data);
	nimln(329, "nativesockets.nim");
	nimln(334, "nativesockets.nim");
	s0 = gethostbyaddr(((void*) ((&myaddr0))), ((socklen_t) (((NI)sizeof(struct in_addr)))), AF_INET);
	nimln(336, "nativesockets.nim");
	{
		NI32 LOC5;
		NCSTRING LOC6;
		NimStringDesc* LOC7;
		if (!(s0 == NIM_NIL)) goto LA3;
		nimln(337, "nativesockets.nim");
		LOC5 = (NI32)0;
		LOC5 = oslasterror_130619_2125978480();
		LOC6 = (NCSTRING)0;
		LOC6 = (char *)hstrerror(h_errno);
		LOC7 = (NimStringDesc*)0;
		LOC7 = cstrToNimstr(LOC6);
		raiseoserror_130603_2125978480(LOC5, LOC7);
	}
	LA3: ;
	nimln(339, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s0).h_name));
	nimln(340, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringarraytoseq_15422_1689653243((*s0).h_aliases));
	nimln(344, "nativesockets.nim");
	{
		if (!((*s0).h_addrtype == AF_INET)) goto LA10;
		nimln(345, "nativesockets.nim");
		(*Result).addrtype = ((Domain147604) 2);
	}
	goto LA8;
	LA10: ;
	{
		nimln(346, "nativesockets.nim");
		if (!((*s0).h_addrtype == AF_INET6)) goto LA13;
		nimln(347, "nativesockets.nim");
		(*Result).addrtype = ((Domain147604) 23);
	}
	goto LA8;
	LA13: ;
	{
		NI32 LOC16;
		nimln(349, "nativesockets.nim");
		LOC16 = (NI32)0;
		LOC16 = oslasterror_130619_2125978480();
		raiseoserror_130603_2125978480(LOC16, ((NimStringDesc*) &T466562973_3));
	}
	LA8: ;
	nimln(350, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).addrlist), cstringarraytoseq_15422_1689653243((*s0).h_addr_list));
	nimln(351, "nativesockets.nim");
	(*Result).length = ((NI) ((*s0).h_length));
	popFrame();
}

N_NIMCALL(void, gethostbyname_150204_466562973)(NimStringDesc* name0, Hostent147612* Result) {
	struct hostent* s0;
	nimfr("getHostByName", "nativesockets.nim")
	nimln(358, "nativesockets.nim");
	s0 = gethostbyname(name0->data);
	nimln(359, "nativesockets.nim");
	{
		NI32 LOC5;
		if (!(s0 == NIM_NIL)) goto LA3;
		LOC5 = (NI32)0;
		LOC5 = oslasterror_130619_2125978480();
		raiseoserror_130603_2125978480(LOC5, ((NimStringDesc*) &T466562973_4));
	}
	LA3: ;
	nimln(360, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s0).h_name));
	nimln(361, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringarraytoseq_15422_1689653243((*s0).h_aliases));
	nimln(365, "nativesockets.nim");
	{
		if (!((*s0).h_addrtype == AF_INET)) goto LA8;
		nimln(366, "nativesockets.nim");
		(*Result).addrtype = ((Domain147604) 2);
	}
	goto LA6;
	LA8: ;
	{
		nimln(367, "nativesockets.nim");
		if (!((*s0).h_addrtype == AF_INET6)) goto LA11;
		nimln(368, "nativesockets.nim");
		(*Result).addrtype = ((Domain147604) 23);
	}
	goto LA6;
	LA11: ;
	{
		NI32 LOC14;
		nimln(370, "nativesockets.nim");
		LOC14 = (NI32)0;
		LOC14 = oslasterror_130619_2125978480();
		raiseoserror_130603_2125978480(LOC14, ((NimStringDesc*) &T466562973_3));
	}
	LA6: ;
	nimln(371, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).addrlist), cstringarraytoseq_15422_1689653243((*s0).h_addr_list));
	nimln(372, "nativesockets.nim");
	(*Result).length = ((NI) ((*s0).h_length));
	popFrame();
}

N_NIMCALL(Domain147604, getsockdomain_150602_466562973)(int socket0) {
	Domain147604 result0;
	struct sockaddr name0;
	socklen_t namelen0;
	nimfr("getSockDomain", "nativesockets.nim")
	result0 = (Domain147604)0;
	memset((void*)(&name0), 0, sizeof(name0));
	nimln(377, "nativesockets.nim");
	namelen0 = ((socklen_t) (((NI)sizeof(struct sockaddr))));
	nimln(378, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(379, "nativesockets.nim");
		nimln(378, "nativesockets.nim");
		LOC3 = (int)0;
		LOC3 = getsockname(socket0, ((struct sockaddr*) ((&name0))), (&namelen0));
		if (!(LOC3 == ((NI32) -1))) goto LA4;
		nimln(380, "nativesockets.nim");
		LOC6 = (NI32)0;
		LOC6 = oslasterror_130619_2125978480();
		raiseoserror_130603_2125978480(LOC6, ((NimStringDesc*) &T466562973_4));
	}
	LA4: ;
	nimln(381, "nativesockets.nim");
	{
		if (!(name0.sa_family == nativeafinet_147652_466562973)) goto LA9;
		nimln(382, "nativesockets.nim");
		result0 = ((Domain147604) 2);
	}
	goto LA7;
	LA9: ;
	{
		nimln(383, "nativesockets.nim");
		if (!(name0.sa_family == nativeafinet6_147653_466562973)) goto LA12;
		nimln(384, "nativesockets.nim");
		result0 = ((Domain147604) 23);
	}
	goto LA7;
	LA12: ;
	{
		NI32 LOC15;
		nimln(386, "nativesockets.nim");
		LOC15 = (NI32)0;
		LOC15 = oslasterror_130619_2125978480();
		raiseoserror_130603_2125978480(LOC15, ((NimStringDesc*) &T466562973_5));
	}
	LA7: ;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, getaddrstring_150613_466562973)(struct sockaddr* sockaddr0) {
	NimStringDesc* result0;
	nimfr("getAddrString", "nativesockets.nim")
	result0 = (NimStringDesc*)0;
	nimln(391, "nativesockets.nim");
	{
		NCSTRING LOC5;
		if (!((*sockaddr0).sa_family == nativeafinet_147652_466562973)) goto LA3;
		nimln(392, "nativesockets.nim");
		LOC5 = (NCSTRING)0;
		LOC5 = inet_ntoa((*((struct sockaddr_in*) (sockaddr0))).sin_addr);
		result0 = cstrToNimstr(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		struct in6_addr* addr60;
		NCSTRING LOC9;
		nimln(393, "nativesockets.nim");
		if (!((*sockaddr0).sa_family == nativeafinet6_147653_466562973)) goto LA7;
		nimln(396, "nativesockets.nim");
		result0 = mnewString(((NI)chckRange(INET6_ADDRSTRLEN, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln(397, "nativesockets.nim");
		addr60 = (&(*((struct sockaddr_in6*) (sockaddr0))).sin6_addr);
		nimln(398, "nativesockets.nim");
		nimln(399, "nativesockets.nim");
		LOC9 = (NCSTRING)0;
		LOC9 = (char *)inet_ntop(AF_INET6, ((void*) (addr60)), result0->data, ((NI32)chckRange((result0 ? result0->Sup.len : 0), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
		nimln(400, "nativesockets.nim");
		{
			int LOC12;
			nimln(347, "system.nim");
			nimln(400, "nativesockets.nim");
			LOC12 = (int)0;
			LOC12 = IN6_IS_ADDR_V4MAPPED(addr60);
			if (!!((LOC12 == ((NI32) 0)))) goto LA13;
			nimln(401, "nativesockets.nim");
			result0 = copyStr(result0, ((NI) 7));
		}
		LA13: ;
	}
	goto LA1;
	LA7: ;
	{
		NI32 LOC16;
		nimln(403, "nativesockets.nim");
		LOC16 = (NI32)0;
		LOC16 = oslasterror_130619_2125978480();
		raiseoserror_130603_2125978480(LOC16, ((NimStringDesc*) &T466562973_6));
	}
	LA1: ;
	popFrame();
	return result0;
}

N_NIMCALL(NU16, getsockname_150806_466562973)(int socket0) {
	NU16 result0;
	struct sockaddr_in name0;
	socklen_t namelen0;
	nimfr("getSockName", "nativesockets.nim")
	result0 = (NU16)0;
	memset((void*)(&name0), 0, sizeof(name0));
	nimln(412, "nativesockets.nim");
	name0.sin_family = AF_INET;
	nimln(415, "nativesockets.nim");
	namelen0 = ((socklen_t) (((NI)sizeof(struct sockaddr_in))));
	nimln(416, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(417, "nativesockets.nim");
		nimln(416, "nativesockets.nim");
		LOC3 = (int)0;
		LOC3 = getsockname(socket0, ((struct sockaddr*) ((&name0))), (&namelen0));
		if (!(LOC3 == ((NI32) -1))) goto LA4;
		nimln(418, "nativesockets.nim");
		LOC6 = (NI32)0;
		LOC6 = oslasterror_130619_2125978480();
		raiseoserror_130603_2125978480(LOC6, ((NimStringDesc*) &T466562973_4));
	}
	LA4: ;
	nimln(419, "nativesockets.nim");
	result0 = ntohs_149088_466562973(name0.sin_port);
	popFrame();
	return result0;
}

N_NIMCALL(void, getlocaladdr_151008_466562973)(int socket0, Domain147604 domain0, TY151012* Result) {
	nimfr("getLocalAddr", "nativesockets.nim")
	nimln(425, "nativesockets.nim");
	switch (domain0) {
	case ((Domain147604) 2):
	{
		struct sockaddr_in name0;
		socklen_t namelen0;
		NCSTRING LOC8;
		memset((void*)(&name0), 0, sizeof(name0));
		nimln(431, "nativesockets.nim");
		name0.sin_family = AF_INET;
		nimln(432, "nativesockets.nim");
		namelen0 = ((socklen_t) (((NI)sizeof(struct sockaddr_in))));
		nimln(433, "nativesockets.nim");
		{
			int LOC4;
			NI32 LOC7;
			nimln(434, "nativesockets.nim");
			nimln(433, "nativesockets.nim");
			LOC4 = (int)0;
			LOC4 = getsockname(socket0, ((struct sockaddr*) ((&name0))), (&namelen0));
			if (!(LOC4 == ((NI32) -1))) goto LA5;
			nimln(435, "nativesockets.nim");
			LOC7 = (NI32)0;
			LOC7 = oslasterror_130619_2125978480();
			raiseoserror_130603_2125978480(LOC7, ((NimStringDesc*) &T466562973_4));
		}
		LA5: ;
		nimln(436, "nativesockets.nim");
		LOC8 = (NCSTRING)0;
		LOC8 = inet_ntoa(name0.sin_addr);
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(LOC8));
		nimln(437, "nativesockets.nim");
		(*Result).Field1 = ntohs_149088_466562973(name0.sin_port);
	}
	break;
	case ((Domain147604) 23):
	{
		struct sockaddr_in6 name0;
		socklen_t namelen0;
		TY151406 buf0;
		memset((void*)(&name0), 0, sizeof(name0));
		nimln(443, "nativesockets.nim");
		name0.sin6_family = AF_INET6;
		nimln(444, "nativesockets.nim");
		namelen0 = ((socklen_t) (((NI)sizeof(struct sockaddr_in6))));
		nimln(445, "nativesockets.nim");
		{
			int LOC12;
			NI32 LOC15;
			nimln(446, "nativesockets.nim");
			nimln(445, "nativesockets.nim");
			LOC12 = (int)0;
			LOC12 = getsockname(socket0, ((struct sockaddr*) ((&name0))), (&namelen0));
			if (!(LOC12 == ((NI32) -1))) goto LA13;
			nimln(447, "nativesockets.nim");
			LOC15 = (NI32)0;
			LOC15 = oslasterror_130619_2125978480();
			raiseoserror_130603_2125978480(LOC15, ((NimStringDesc*) &T466562973_4));
		}
		LA13: ;
		memset((void*)buf0, 0, sizeof(buf0));
		nimln(450, "nativesockets.nim");
		{
			NCSTRING LOC18;
			NI32 LOC21;
			nimln(451, "nativesockets.nim");
			nimln(450, "nativesockets.nim");
			nimln(451, "nativesockets.nim");
			LOC18 = (NCSTRING)0;
			LOC18 = (char *)inet_ntop(name0.sin6_family, ((void*) ((&name0))), ((NCSTRING) (buf0)), ((NI32)chckRange(((NI)sizeof(TY151406)), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
			if (!LOC18 == 0) goto LA19;
			nimln(452, "nativesockets.nim");
			LOC21 = (NI32)0;
			LOC21 = oslasterror_130619_2125978480();
			raiseoserror_130603_2125978480(LOC21, ((NimStringDesc*) &T466562973_4));
		}
		LA19: ;
		nimln(453, "nativesockets.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(((NCSTRING) (buf0))));
		(*Result).Field1 = ntohs_149088_466562973(name0.sin6_port);
	}
	break;
	default:
	{
		nimln(455, "nativesockets.nim");
		raiseoserror_130603_2125978480(((NI32) -1), ((NimStringDesc*) &T466562973_7));
	}
	break;
	}
	popFrame();
}

N_NIMCALL(void, getpeeraddr_151419_466562973)(int socket0, Domain147604 domain0, TY151012* Result) {
	nimfr("getPeerAddr", "nativesockets.nim")
	nimln(461, "nativesockets.nim");
	switch (domain0) {
	case ((Domain147604) 2):
	{
		struct sockaddr_in name0;
		socklen_t namelen0;
		NCSTRING LOC8;
		memset((void*)(&name0), 0, sizeof(name0));
		nimln(467, "nativesockets.nim");
		name0.sin_family = AF_INET;
		nimln(468, "nativesockets.nim");
		namelen0 = ((socklen_t) (((NI)sizeof(struct sockaddr_in))));
		nimln(469, "nativesockets.nim");
		{
			int LOC4;
			NI32 LOC7;
			nimln(470, "nativesockets.nim");
			nimln(469, "nativesockets.nim");
			LOC4 = (int)0;
			LOC4 = getpeername(socket0, ((struct sockaddr*) ((&name0))), (&namelen0));
			if (!(LOC4 == ((NI32) -1))) goto LA5;
			nimln(471, "nativesockets.nim");
			LOC7 = (NI32)0;
			LOC7 = oslasterror_130619_2125978480();
			raiseoserror_130603_2125978480(LOC7, ((NimStringDesc*) &T466562973_4));
		}
		LA5: ;
		nimln(472, "nativesockets.nim");
		LOC8 = (NCSTRING)0;
		LOC8 = inet_ntoa(name0.sin_addr);
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(LOC8));
		nimln(473, "nativesockets.nim");
		(*Result).Field1 = ntohs_149088_466562973(name0.sin_port);
	}
	break;
	case ((Domain147604) 23):
	{
		struct sockaddr_in6 name0;
		socklen_t namelen0;
		TY151406 buf0;
		memset((void*)(&name0), 0, sizeof(name0));
		nimln(479, "nativesockets.nim");
		name0.sin6_family = AF_INET6;
		nimln(480, "nativesockets.nim");
		namelen0 = ((socklen_t) (((NI)sizeof(struct sockaddr_in6))));
		nimln(481, "nativesockets.nim");
		{
			int LOC12;
			NI32 LOC15;
			nimln(482, "nativesockets.nim");
			nimln(481, "nativesockets.nim");
			LOC12 = (int)0;
			LOC12 = getpeername(socket0, ((struct sockaddr*) ((&name0))), (&namelen0));
			if (!(LOC12 == ((NI32) -1))) goto LA13;
			nimln(483, "nativesockets.nim");
			LOC15 = (NI32)0;
			LOC15 = oslasterror_130619_2125978480();
			raiseoserror_130603_2125978480(LOC15, ((NimStringDesc*) &T466562973_4));
		}
		LA13: ;
		memset((void*)buf0, 0, sizeof(buf0));
		nimln(486, "nativesockets.nim");
		{
			NCSTRING LOC18;
			NI32 LOC21;
			nimln(487, "nativesockets.nim");
			nimln(486, "nativesockets.nim");
			nimln(487, "nativesockets.nim");
			LOC18 = (NCSTRING)0;
			LOC18 = (char *)inet_ntop(name0.sin6_family, ((void*) ((&name0))), ((NCSTRING) (buf0)), ((NI32)chckRange(((NI)sizeof(TY151406)), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
			if (!LOC18 == 0) goto LA19;
			nimln(488, "nativesockets.nim");
			LOC21 = (NI32)0;
			LOC21 = oslasterror_130619_2125978480();
			raiseoserror_130603_2125978480(LOC21, ((NimStringDesc*) &T466562973_4));
		}
		LA19: ;
		nimln(489, "nativesockets.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(((NCSTRING) (buf0))));
		(*Result).Field1 = ntohs_149088_466562973(name0.sin6_port);
	}
	break;
	default:
	{
		nimln(491, "nativesockets.nim");
		raiseoserror_130603_2125978480(((NI32) -1), ((NimStringDesc*) &T466562973_7));
	}
	break;
	}
	popFrame();
}

N_NIMCALL(NI, getsockoptint_151819_466562973)(int socket0, NI level0, NI optname0) {
	NI result0;
	int res0;
	socklen_t size0;
	nimfr("getSockOptInt", "nativesockets.nim")
	result0 = (NI)0;
	res0 = (int)0;
	nimln(497, "nativesockets.nim");
	size0 = ((socklen_t) 4);
	nimln(498, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(499, "nativesockets.nim");
		nimln(498, "nativesockets.nim");
		LOC3 = (int)0;
		LOC3 = getsockopt(socket0, ((int)chckRange(level0, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(optname0, ((int) (-2147483647 -1)), ((int) 2147483647))), ((void*) ((&res0))), (&size0));
		if (!(LOC3 < ((NI32) 0))) goto LA4;
		nimln(500, "nativesockets.nim");
		LOC6 = (NI32)0;
		LOC6 = oslasterror_130619_2125978480();
		raiseoserror_130603_2125978480(LOC6, ((NimStringDesc*) &T466562973_4));
	}
	LA4: ;
	nimln(501, "nativesockets.nim");
	result0 = ((NI) (res0));
	popFrame();
	return result0;
}

N_NIMCALL(void, setsockoptint_151831_466562973)(int socket0, NI level0, NI optname0, NI optval0) {
	int value0;
	nimfr("setSockOptInt", "nativesockets.nim")
	nimln(506, "nativesockets.nim");
	value0 = ((int)chckRange(optval0, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln(507, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(508, "nativesockets.nim");
		nimln(507, "nativesockets.nim");
		LOC3 = (int)0;
		LOC3 = setsockopt(socket0, ((int)chckRange(level0, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(optname0, ((int) (-2147483647 -1)), ((int) 2147483647))), ((void*) ((&value0))), ((socklen_t) 4));
		if (!(LOC3 < ((NI32) 0))) goto LA4;
		nimln(509, "nativesockets.nim");
		LOC6 = (NI32)0;
		LOC6 = oslasterror_130619_2125978480();
		raiseoserror_130603_2125978480(LOC6, ((NimStringDesc*) &T466562973_4));
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(void, setblocking_151839_466562973)(int s0, NIM_BOOL blocking0) {
	NI x0;
	int LOC1;
	nimfr("setBlocking", "nativesockets.nim")
	nimln(520, "nativesockets.nim");
	LOC1 = (int)0;
	LOC1 = fcntl(s0, F_GETFL, ((NI) 0));
	x0 = ((NI) (LOC1));
	nimln(521, "nativesockets.nim");
	{
		NI32 LOC6;
		if (!(x0 == ((NI) -1))) goto LA4;
		nimln(522, "nativesockets.nim");
		LOC6 = (NI32)0;
		LOC6 = oslasterror_130619_2125978480();
		raiseoserror_130603_2125978480(LOC6, ((NimStringDesc*) &T466562973_4));
	}
	goto LA2;
	LA4: ;
	{
		NI mode0;
		nimln(524, "nativesockets.nim");
		{
			if (!blocking0) goto LA10;
			mode0 = (NI)(x0 & ((NI) ((NI32)((NU32) ~(O_NONBLOCK)))));
		}
		goto LA8;
		LA10: ;
		{
			mode0 = (NI)(x0 | ((NI) (O_NONBLOCK)));
		}
		LA8: ;
		nimln(525, "nativesockets.nim");
		{
			int LOC15;
			NI32 LOC18;
			LOC15 = (int)0;
			LOC15 = fcntl(s0, F_SETFL, mode0);
			if (!(LOC15 == ((NI32) -1))) goto LA16;
			nimln(526, "nativesockets.nim");
			LOC18 = (NI32)0;
			LOC18 = oslasterror_130619_2125978480();
			raiseoserror_130603_2125978480(LOC18, ((NimStringDesc*) &T466562973_4));
		}
		LA16: ;
	}
	LA2: ;
	popFrame();
}

static N_INLINE(NI, divInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		if (!(b0 == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (NIM_BOOL)0;
		LOC7 = (a0 == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b0 == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result0 = (NI)(a0 / b0);
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(struct timeval, timevalfrommilliseconds_152022_466562973)(NI timeout0) {
	struct timeval result0;
	nimfr("timeValFromMilliseconds", "nativesockets.nim")
	memset((void*)(&result0), 0, sizeof(result0));
	nimln(529, "nativesockets.nim");
	{
		NI seconds0;
		NI T466562973_8;
		NI T466562973_9;
		NI T466562973_10;
		NI T466562973_11;
		nimln(347, "system.nim");
		if (!!((timeout0 == ((NI) -1)))) goto LA3;
		nimln(530, "nativesockets.nim");
		T466562973_8 = divInt(timeout0, ((NI) 1000));
		seconds0 = (NI)(T466562973_8);
		nimln(531, "nativesockets.nim");
		result0.tv_sec = ((NI) (((NI32)chckRange(seconds0, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)))));
		nimln(532, "nativesockets.nim");
		T466562973_9 = mulInt(seconds0, ((NI) 1000));
		T466562973_10 = subInt(timeout0, (NI)(T466562973_9));
		T466562973_11 = mulInt((NI)(T466562973_10), ((NI) 1000));
		result0.tv_usec = ((NI) (((NI32)chckRange((NI)(T466562973_11), ((NI32) (-2147483647 -1)), ((NI32) 2147483647)))));
	}
	LA3: ;
	popFrame();
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, createfdset_152031_466562973)(fd_set* fd0, TY152035* s0, NI* m0) {
	nimfr("createFdSet", "nativesockets.nim")
	nimln(535, "nativesockets.nim");
	FD_ZERO(fd0);
	{
		int i_152202_466562973;
		NI i_152219_466562973;
		NI L_152221_466562973;
		i_152202_466562973 = (int)0;
		nimln(3440, "system.nim");
		i_152219_466562973 = ((NI) 0);
		nimln(3441, "system.nim");
		L_152221_466562973 = (s0 ? s0->Sup.len : 0);
		{
			nimln(3442, "system.nim");
			while (1) {
				NI T466562973_12;
				if (!(i_152219_466562973 < L_152221_466562973)) goto LA3;
				nimln(3443, "system.nim");
				if ((NU)(i_152219_466562973) >= (NU)(s0->Sup.len)) raiseIndexError();
				i_152202_466562973 = s0->data[i_152219_466562973];
				nimln(537, "nativesockets.nim");
				(*m0) = (((*m0) >= ((NI) (i_152202_466562973))) ? (*m0) : ((NI) (i_152202_466562973)));
				nimln(538, "nativesockets.nim");
				FD_SET(i_152202_466562973, fd0);
				nimln(3444, "system.nim");
				T466562973_12 = addInt(i_152219_466562973, ((NI) 1));
				i_152219_466562973 = (NI)(T466562973_12);
				nimln(3445, "system.nim");
				{
					if (!!(((s0 ? s0->Sup.len : 0) == L_152221_466562973))) goto LA6;
					failedassertimpl_91639_1689653243(((NimStringDesc*) &T466562973_13));
				}
				LA6: ;
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, prunesocketset_152222_466562973)(TY152035** s0, fd_set* fd0) {
	NI i0;
	NI L0;
	nimfr("pruneSocketSet", "nativesockets.nim")
	nimln(541, "nativesockets.nim");
	i0 = ((NI) 0);
	nimln(542, "nativesockets.nim");
	L0 = ((*s0) ? (*s0)->Sup.len : 0);
	{
		nimln(543, "nativesockets.nim");
		while (1) {
			if (!(i0 < L0)) goto LA2;
			nimln(544, "nativesockets.nim");
			{
				int LOC5;
				NI T466562973_14;
				NI T466562973_15;
				if ((NU)(i0) >= (NU)((*s0)->Sup.len)) raiseIndexError();
				LOC5 = (int)0;
				LOC5 = FD_ISSET((*s0)->data[i0], fd0);
				if (!(LOC5 == ((NI32) 0))) goto LA6;
				nimln(545, "nativesockets.nim");
				if ((NU)(i0) >= (NU)((*s0)->Sup.len)) raiseIndexError();
				T466562973_14 = subInt(L0, ((NI) 1));
				if ((NU)((NI)(T466562973_14)) >= (NU)((*s0)->Sup.len)) raiseIndexError();
				(*s0)->data[i0] = (*s0)->data[(NI)(T466562973_14)];
				nimln(546, "nativesockets.nim");
				T466562973_15 = subInt(L0, ((NI) 1));
				L0 = (NI)(T466562973_15);
			}
			goto LA3;
			LA6: ;
			{
				NI T466562973_16;
				nimln(548, "nativesockets.nim");
				T466562973_16 = addInt(i0, ((NI) 1));
				i0 = (NI)(T466562973_16);
			}
			LA3: ;
		} LA2: ;
	}
	nimln(549, "nativesockets.nim");
	(*s0) = (TY152035*) setLengthSeq(&((*s0))->Sup, sizeof(int), ((NI)chckRange(L0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
}

N_NIMCALL(NI, select_152277_466562973)(TY152035** readfds0, NI timeout0) {
	NI result0;
	struct timeval tv0;
	fd_set rd0;
	NI m0;
	nimfr("select", "nativesockets.nim")
	result0 = (NI)0;
	nimln(559, "nativesockets.nim");
	tv0 = timevalfrommilliseconds_152022_466562973(timeout0);
	memset((void*)(&rd0), 0, sizeof(rd0));
	nimln(562, "nativesockets.nim");
	m0 = ((NI) 0);
	nimln(563, "nativesockets.nim");
	createfdset_152031_466562973((&rd0), (*readfds0), (&m0));
	nimln(565, "nativesockets.nim");
	{
		NI T466562973_17;
		int LOC5;
		nimln(347, "system.nim");
		if (!!((timeout0 == ((NI) -1)))) goto LA3;
		nimln(566, "nativesockets.nim");
		T466562973_17 = addInt(m0, ((NI) 1));
		LOC5 = (int)0;
		LOC5 = select(((int)chckRange((NI)(T466562973_17), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd0), NIM_NIL, NIM_NIL, (&tv0));
		result0 = ((NI) (LOC5));
	}
	goto LA1;
	LA3: ;
	{
		NI T466562973_18;
		int LOC7;
		nimln(568, "nativesockets.nim");
		T466562973_18 = addInt(m0, ((NI) 1));
		LOC7 = (int)0;
		LOC7 = select(((int)chckRange((NI)(T466562973_18), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd0), NIM_NIL, NIM_NIL, NIM_NIL);
		result0 = ((NI) (LOC7));
	}
	LA1: ;
	nimln(570, "nativesockets.nim");
	prunesocketset_152222_466562973(readfds0, (&rd0));
	popFrame();
	return result0;
}

N_NIMCALL(NI, selectwrite_152328_466562973)(TY152035** writefds0, NI timeout0) {
	NI result0;
	struct timeval tv0;
	fd_set wr0;
	NI m0;
	nimfr("selectWrite", "nativesockets.nim")
	result0 = (NI)0;
	nimln(581, "nativesockets.nim");
	tv0 = timevalfrommilliseconds_152022_466562973(timeout0);
	memset((void*)(&wr0), 0, sizeof(wr0));
	nimln(584, "nativesockets.nim");
	m0 = ((NI) 0);
	nimln(585, "nativesockets.nim");
	createfdset_152031_466562973((&wr0), (*writefds0), (&m0));
	nimln(587, "nativesockets.nim");
	{
		NI T466562973_19;
		int LOC5;
		nimln(347, "system.nim");
		if (!!((timeout0 == ((NI) -1)))) goto LA3;
		nimln(588, "nativesockets.nim");
		T466562973_19 = addInt(m0, ((NI) 1));
		LOC5 = (int)0;
		LOC5 = select(((int)chckRange((NI)(T466562973_19), ((int) (-2147483647 -1)), ((int) 2147483647))), NIM_NIL, (&wr0), NIM_NIL, (&tv0));
		result0 = ((NI) (LOC5));
	}
	goto LA1;
	LA3: ;
	{
		NI T466562973_20;
		int LOC7;
		nimln(590, "nativesockets.nim");
		T466562973_20 = addInt(m0, ((NI) 1));
		LOC7 = (int)0;
		LOC7 = select(((int)chckRange((NI)(T466562973_20), ((int) (-2147483647 -1)), ((int) 2147483647))), NIM_NIL, (&wr0), NIM_NIL, NIM_NIL);
		result0 = ((NI) (LOC7));
	}
	LA1: ;
	nimln(592, "nativesockets.nim");
	prunesocketset_152222_466562973(writefds0, (&wr0));
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsInit000)(void) {
	nimfr("nativesockets", "nativesockets.nim")
	nimln(104, "nativesockets.nim");
	osinvalidsocket_147651_466562973 = ((int) -1);
	nimln(105, "nativesockets.nim");
	nativeafinet_147652_466562973 = AF_INET;
	nimln(106, "nativesockets.nim");
	nativeafinet6_147653_466562973 = AF_INET6;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsDatInit000)(void) {
static TNimNode* T466562973_21[3];
NI T466562973_23;
static char* NIM_CONST T466562973_22[3] = {
"AF_UNIX", 
"AF_INET", 
"AF_INET6"};
static TNimNode* T466562973_24[4];
NI T466562973_26;
static char* NIM_CONST T466562973_25[4] = {
"SOCK_STREAM", 
"SOCK_DGRAM", 
"SOCK_RAW", 
"SOCK_SEQPACKET"};
static TNimNode* T466562973_27[6];
NI T466562973_29;
static char* NIM_CONST T466562973_28[6] = {
"IPPROTO_TCP", 
"IPPROTO_UDP", 
"IPPROTO_IP", 
"IPPROTO_IPV6", 
"IPPROTO_RAW", 
"IPPROTO_ICMP"};
static TNimNode T466562973_0[16];
NTI147604.size = sizeof(Domain147604);
NTI147604.kind = 14;
NTI147604.base = 0;
NTI147604.flags = 3;
for (T466562973_23 = 0; T466562973_23 < 3; T466562973_23++) {
T466562973_0[T466562973_23+0].kind = 1;
T466562973_0[T466562973_23+0].offset = T466562973_23;
T466562973_0[T466562973_23+0].name = T466562973_22[T466562973_23];
T466562973_21[T466562973_23] = &T466562973_0[T466562973_23+0];
}
T466562973_0[0].offset = 0;
T466562973_0[1].offset = 2;
T466562973_0[2].offset = 23;
T466562973_0[3].len = 3; T466562973_0[3].kind = 2; T466562973_0[3].sons = &T466562973_21[0];
NTI147604.node = &T466562973_0[3];
NTI147604.flags = 1<<2;
NTI147606.size = sizeof(Socktype147606);
NTI147606.kind = 14;
NTI147606.base = 0;
NTI147606.flags = 3;
for (T466562973_26 = 0; T466562973_26 < 4; T466562973_26++) {
T466562973_0[T466562973_26+4].kind = 1;
T466562973_0[T466562973_26+4].offset = T466562973_26;
T466562973_0[T466562973_26+4].name = T466562973_25[T466562973_26];
T466562973_24[T466562973_26] = &T466562973_0[T466562973_26+4];
}
T466562973_0[4].offset = 1;
T466562973_0[5].offset = 2;
T466562973_0[6].offset = 3;
T466562973_0[7].offset = 5;
T466562973_0[8].len = 4; T466562973_0[8].kind = 2; T466562973_0[8].sons = &T466562973_24[0];
NTI147606.node = &T466562973_0[8];
NTI147606.flags = 1<<2;
NTI147608.size = sizeof(Protocol147608);
NTI147608.kind = 14;
NTI147608.base = 0;
NTI147608.flags = 3;
for (T466562973_29 = 0; T466562973_29 < 6; T466562973_29++) {
T466562973_0[T466562973_29+9].kind = 1;
T466562973_0[T466562973_29+9].offset = T466562973_29;
T466562973_0[T466562973_29+9].name = T466562973_28[T466562973_29];
T466562973_27[T466562973_29] = &T466562973_0[T466562973_29+9];
}
T466562973_0[9].offset = 6;
T466562973_0[10].offset = 17;
T466562973_0[11].offset = 18;
T466562973_0[12].offset = 19;
T466562973_0[13].offset = 20;
T466562973_0[14].offset = 21;
T466562973_0[15].len = 6; T466562973_0[15].kind = 2; T466562973_0[15].sons = &T466562973_27[0];
NTI147608.node = &T466562973_0[15];
NTI147608.flags = 1<<2;
}

