/* Generated by Nim Compiler v0.15.0 */
/*   (c) 2016 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.15.0/nim/lib -o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/stdlib_os.o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/stdlib_os.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <errno.h>
typedef struct TY15205 TY15205;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Oserror3630 Oserror3630;
typedef struct Systemerror3626 Systemerror3626;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct Cell47705 Cell47705;
typedef struct Cellseq47721 Cellseq47721;
typedef struct Gcheap50218 Gcheap50218;
typedef struct Gcstack50216 Gcstack50216;
typedef struct Memregion29886 Memregion29886;
typedef struct Smallchunk29840 Smallchunk29840;
typedef struct Llchunk29880 Llchunk29880;
typedef struct Bigchunk29842 Bigchunk29842;
typedef struct Intset29814 Intset29814;
typedef struct Trunk29810 Trunk29810;
typedef struct Avlnode29884 Avlnode29884;
typedef struct Gcstat50214 Gcstat50214;
typedef struct Cellset47717 Cellset47717;
typedef struct Pagedesc47713 Pagedesc47713;
typedef struct Basechunk29838 Basechunk29838;
typedef struct Freecell29830 Freecell29830;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 Tnimkind3403;
typedef NU8 Tnimtypeflag3409Set;
typedef N_NIMCALL_PTR(void, TY3489) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3403 kind;
Tnimtypeflag3409Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
typedef NU8 Tnimnodekind3405;
struct  TNimNode  {
Tnimnodekind3405 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, Globalmarkerproc56202) (void);
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Systemerror3626  {
  Exception Sup;
};
struct  Oserror3630  {
  Systemerror3626 Sup;
NI32 errorcode;
};
struct  Cell47705  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47721  {
NI len;
NI cap;
Cell47705** d;
};
typedef Smallchunk29840* TY29901[512];
typedef Trunk29810* Trunkbuckets29812[256];
struct  Intset29814  {
Trunkbuckets29812 data;
};
struct  Memregion29886  {
NI minlargeobj;
NI maxlargeobj;
TY29901 freesmallchunks;
Llchunk29880* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29842* freechunkslist;
Intset29814 chunkstarts;
Avlnode29884* root;
Avlnode29884* deleted;
Avlnode29884* last;
Avlnode29884* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat50214  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47717  {
NI counter;
NI max;
Pagedesc47713* head;
Pagedesc47713** data;
};
struct  Gcheap50218  {
Gcstack50216* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47721 zct;
Cellseq47721 decstack;
Cellseq47721 tempstack;
NI recgclock;
Memregion29886 region;
Gcstat50214 stat;
Cellset47717 marked;
Cellseq47721 additionalroots;
};
struct  Gcstack50216  {
Gcstack50216* prev;
Gcstack50216* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk29838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29840  {
  Basechunk29838 Sup;
Smallchunk29840* next;
Smallchunk29840* prev;
Freecell29830* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29880  {
NI size;
NI acc;
Llchunk29880* next;
};
struct  Bigchunk29842  {
  Basechunk29838 Sup;
Bigchunk29842* next;
Bigchunk29842* prev;
NI align;
NF data;
};
typedef NI TY29819[8];
struct  Trunk29810  {
Trunk29810* next;
NI key;
TY29819 bits;
};
typedef Avlnode29884* TY29891[2];
struct  Avlnode29884  {
TY29891 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47713  {
Pagedesc47713* next;
NI key;
TY29819 bits;
};
struct  Freecell29830  {
Freecell29830* next;
NI zerofield;
};
struct TY15205 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
N_NIMCALL(void, T2125978480_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(Globalmarkerproc56202 markerproc0);
static N_INLINE(NimStringDesc*, pop_138639_1689653243)(TY15205** s0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src0);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq0, NI elemsize0, NI newlen0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21601_1689653243)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
N_NIMCALL(NimStringDesc*, oserrormsg_130411_2125978480)(NI32 errorcode0);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell47705*, usrtocell_51840_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_53001_1689653243)(Cell47705* c0);
N_NOINLINE(void, addzct_51817_1689653243)(Cellseq47721* s0, Cell47705* c0);
static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0);
static N_INLINE(void, copymem_7485_1689653243)(void* dest0, void* source0, NI size0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space0);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p0);
N_NIMCALL(void, raiseException)(Exception* e0, NCSTRING ename0);
STRING_LITERAL(T2125978480_4, "", 0);
STRING_LITERAL(T2125978480_5, "\012Additional info: ", 18);
STRING_LITERAL(T2125978480_6, "unknown OS error", 16);
NIM_BOOL envcomputed_135001_2125978480;
TY15205* environment_135003_2125978480;
extern TNimType NTI15205; /* seq[string] */
extern TFrame* frameptr_18836_1689653243;
extern int cmdCount;
extern NCSTRING* cmdLine;
extern TNimType NTI130607; /* ref OSError */
extern TNimType NTI3630; /* OSError */
extern Gcheap50218 gch_50258_1689653243;
N_NIMCALL(void, T2125978480_2)(void) {
	nimGCvisit((void*)environment_135003_2125978480, 0);
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18836_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18836_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18836_1689653243;
	frameptr_18836_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21601_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18836_1689653243 = (*frameptr_18836_1689653243).prev;
}

static N_INLINE(NimStringDesc*, pop_138639_1689653243)(TY15205** s0) {
	NimStringDesc* result0;
	NI L0;
	NI T2125978480_3;
	nimfr("pop", "system.nim")
	result0 = (NimStringDesc*)0;
	nimln(2215, "system.nim");
	T2125978480_3 = subInt(((*s0) ? (*s0)->Sup.len : 0), ((NI) 1));
	L0 = (NI)(T2125978480_3);
	nimln(2216, "system.nim");
	if ((NU)(L0) >= (NU)((*s0)->Sup.len)) raiseIndexError();
	result0 = copyString((*s0)->data[L0]);
	nimln(2217, "system.nim");
	(*s0) = (TY15205*) setLengthSeq(&((*s0))->Sup, sizeof(NimStringDesc*), ((NI)chckRange(L0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, oserrormsg_130411_2125978480)(NI32 errorcode0) {
	NimStringDesc* result0;
	nimfr("osErrorMsg", "os.nim")
	result0 = (NimStringDesc*)0;
	nimln(116, "os.nim");
	result0 = copyString(((NimStringDesc*) &T2125978480_4));
	nimln(132, "os.nim");
	{
		NCSTRING LOC5;
		nimln(347, "system.nim");
		if (!!((errorcode0 == ((NI32) 0)))) goto LA3;
		nimln(133, "os.nim");
		LOC5 = (NCSTRING)0;
		LOC5 = strerror(errorcode0);
		result0 = cstrToNimstr(LOC5);
	}
	LA3: ;
	popFrame();
	return result0;
}

static N_INLINE(Cell47705*, usrtocell_51840_1689653243)(void* usr0) {
	Cell47705* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell47705*)0;
	nimln(134, "gc.nim");
	result0 = ((Cell47705*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell47705))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_53001_1689653243)(Cell47705* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(214, "gc.nim");
	addzct_51817_1689653243((&gch_50258_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(274, "gc.nim");
	{
		Cell47705* c0;
		nimln(347, "system.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(275, "gc.nim");
		c0 = usrtocell_51840_1689653243(src0);
		nimln(182, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(277, "gc.nim");
	{
		Cell47705* c0;
		nimln(347, "system.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(278, "gc.nim");
		c0 = usrtocell_51840_1689653243((*dest0));
		nimln(279, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c0).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(280, "gc.nim");
			rtladdzct_53001_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(281, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

static N_INLINE(void, copymem_7485_1689653243)(void* dest0, void* source0, NI size0) {
	void* LOC1;
	LOC1 = (void*)0;
	LOC1 = memcpy(dest0, source0, ((size_t) (size0)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0) {
	copymem_7485_1689653243(((void*) ((&(*dest0).data[((*dest0).Sup.len)- 0]))), ((void*) ((*src0).data)), ((NI) ((NI)((*src0).Sup.len + ((NI) 1)))));
	(*dest0).Sup.len += (*src0).Sup.len;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p0) {
	Cell47705* c0;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(256, "gc.nim");
	c0 = usrtocell_51840_1689653243(p0);
	nimln(258, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c0).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(259, "gc.nim");
		rtladdzct_53001_1689653243(c0);
	}
	LA3: ;
	popFrame();
}

N_NOINLINE(void, raiseoserror_130603_2125978480)(NI32 errorcode0, NimStringDesc* additionalinfo0) {
	Oserror3630* e0;
	nimfr("raiseOSError", "os.nim")
	e0 = (Oserror3630*)0;
	nimln(143, "os.nim");
	e0 = (Oserror3630*) newObj((&NTI130607), sizeof(Oserror3630));
	(*e0).Sup.Sup.Sup.m_type = (&NTI3630);
	nimln(144, "os.nim");
	(*e0).errorcode = errorcode0;
	nimln(145, "os.nim");
	{
		if (!((additionalinfo0 ? additionalinfo0->Sup.len : 0) == ((NI) 0))) goto LA3;
		nimln(146, "os.nim");
		asgnRefNoCycle((void**) (&(*e0).Sup.Sup.message), oserrormsg_130411_2125978480(errorcode0));
	}
	goto LA1;
	LA3: ;
	{
		NimStringDesc* LOC6;
		NimStringDesc* LOC7;
		nimln(148, "os.nim");
		LOC6 = (NimStringDesc*)0;
		LOC7 = (NimStringDesc*)0;
		LOC7 = oserrormsg_130411_2125978480(errorcode0);
		LOC6 = rawNewString(LOC7->Sup.len + additionalinfo0->Sup.len + 18);
appendString(LOC6, LOC7);
appendString(LOC6, ((NimStringDesc*) &T2125978480_5));
appendString(LOC6, additionalinfo0);
		asgnRefNoCycle((void**) (&(*e0).Sup.Sup.message), LOC6);
	}
	LA1: ;
	nimln(149, "os.nim");
	{
		NimStringDesc* LOC12;
		if (!(((*e0).Sup.Sup.message) && ((*e0).Sup.Sup.message)->Sup.len == 0)) goto LA10;
		nimln(150, "os.nim");
		LOC12 = (NimStringDesc*)0;
		LOC12 = (*e0).Sup.Sup.message; (*e0).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &T2125978480_6));
		if (LOC12) nimGCunrefNoCycle(LOC12);
	}
	LA10: ;
	nimln(151, "os.nim");
	raiseException((Exception*)e0, "OSError");
	popFrame();
}

N_NIMCALL(NI32, oslasterror_130619_2125978480)(void) {
	NI32 result0;
	result0 = (NI32)0;
	result0 = errno;
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void) {
	nimfr("os", "os.nim")
nimRegisterGlobalMarker(T2125978480_2);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void) {
}

