/* Generated by Nim Compiler v0.15.0 */
/*   (c) 2016 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.15.0/nim/lib -o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/stdlib_net.o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/stdlib_net.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/socket.h>
#include <netinet/in.h>
#include <string.h>
#include <netdb.h>
typedef struct Socketimpl158406 Socketimpl158406;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef NIM_CHAR TY158420[4001];
typedef NU8 Domain147604;
typedef NU8 Socktype147606;
typedef NU8 Protocol147608;
struct  Socketimpl158406  {
int fd;
NIM_BOOL isbuffered;
union{
struct {TY158420 buffer;
NI currpos;
NI buflen;
} S1;
} isbufferedU;
NI32 lasterror;
Domain147604 domain;
Socktype147606 socktype;
Protocol147608 protocol;
};
typedef NU8 Tnimkind3403;
typedef NU8 Tnimtypeflag3409Set;
typedef N_NIMCALL_PTR(void, TY3489) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3403 kind;
Tnimtypeflag3409Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
typedef NU8 Tnimnodekind3405;
struct  TNimNode  {
Tnimnodekind3405 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NIM_CHAR TY121654[256];
N_NIMCALL(void, T170061329_4)(void* p, NI op);
N_NIMCALL(int, newnativesocket_148001_466562973)(Domain147604 domain0, Socktype147606 socktype0, Protocol147608 protocol0);
N_NOINLINE(void, raiseoserror_130603_2125978480)(NI32 errorcode0, NimStringDesc* additionalinfo0);
N_NIMCALL(NI32, oslasterror_130619_2125978480)(void);
N_NIMCALL(Socketimpl158406*, newsocket_158674_170061329)(int fd0, Domain147604 domain0, Socktype147606 socktype0, Protocol147608 protocol0, NIM_BOOL buffered0);
N_NIMCALL(void, failedassertimpl_91639_1689653243)(NimStringDesc* msg0);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
N_NIMCALL(void, FieldDiscriminantCheck)(NI olddiscval0, NI newdiscval0, TNimNode** a0, NI L0);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f0);
N_NIMCALL(void, setsockoptint_151831_466562973)(int socket0, NI level0, NI optname0, NI optval0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21601_1689653243)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(int, toint_147820_466562973)(Domain147604 domain0);
N_NIMCALL(NU16, ntohs_149088_466562973)(NU16 x0);
N_NIMCALL(NU32, ntohl_148806_466562973)(NU32 x0);
N_NIMCALL(int, bindaddr_148208_466562973)(int socket0, struct sockaddr* name0, socklen_t namelen0);
N_NIMCALL(struct addrinfo*, getaddrinfo_148402_466562973)(NimStringDesc* address0, NU16 port0, Domain147604 domain0, Socktype147606 socktype0, Protocol147608 protocol0);
N_NIMCALL(void, dealloc_148802_466562973)(struct addrinfo* ai0);
N_NIMCALL(NI, sendto_163821_170061329)(Socketimpl158406* socket0, NimStringDesc* address0, NU16 port0, void* data0, NI size0, Domain147604 af0, NI32 flags0);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
TNimNode* NimDT_158406_isbuffered[3];
STRING_LITERAL(T170061329_5, "", 0);
STRING_LITERAL(T170061329_6, "\012  not (fd == osInvalidSocket) ", 31);
STRING_LITERAL(T170061329_7, "currPos", 7);
STRING_LITERAL(T170061329_8, "No valid socket error code available", 36);
TNimType NTI158406; /* SocketImpl */
extern TNimType NTI7408; /* cint */
extern TNimType NTI130; /* bool */
extern TNimType NTI136; /* char */
TNimType NTI158420; /* array[0..4000, char] */
extern TNimType NTI104; /* int */
extern TNimType NTI110; /* int32 */
extern TNimType NTI147604; /* Domain */
extern TNimType NTI147606; /* SockType */
extern TNimType NTI147608; /* Protocol */
TNimType NTI158408; /* Socket */
extern int osinvalidsocket_147651_466562973;
extern TNimNode* NimDT_158406_isbuffered[3];
extern TFrame* frameptr_18836_1689653243;
N_NIMCALL(void, T170061329_4)(void* p, NI op) {
	Socketimpl158406* a;
	NI LOC1;
	a = (Socketimpl158406*)p;
	switch ((*a).isbuffered) {
	case NIM_TRUE:
	LOC1 = (NI)0;
	for (LOC1 = 0; LOC1 < 4001; LOC1++) {
	}
	break;
	case NIM_FALSE:
	break;
	} 
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18836_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18836_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18836_1689653243;
	frameptr_18836_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21601_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18836_1689653243 = (*frameptr_18836_1689653243).prev;
}

N_NIMCALL(Socketimpl158406*, newsocket_158674_170061329)(int fd0, Domain147604 domain0, Socktype147606 socktype0, Protocol147608 protocol0, NIM_BOOL buffered0) {
	Socketimpl158406* result0;
	NIM_BOOL LOC5;
	nimfr("newSocket", "net.nim")
	result0 = (Socketimpl158406*)0;
	nimln(202, "net.nim");
	{
		if (!!(!((fd0 == osinvalidsocket_147651_466562973)))) goto LA3;
		failedassertimpl_91639_1689653243(((NimStringDesc*) &T170061329_6));
	}
	LA3: ;
	nimln(203, "net.nim");
	result0 = (Socketimpl158406*) newObj((&NTI158408), sizeof(Socketimpl158406));
	nimln(204, "net.nim");
	(*result0).fd = fd0;
	nimln(205, "net.nim");
	LOC5 = (NIM_BOOL)0;
	LOC5 = buffered0;
	FieldDiscriminantCheck((NI)(NU)((*result0).isbuffered), (NI)(NU)(LOC5), NimDT_158406_isbuffered, 3);
	(*result0).isbuffered = LOC5;
	nimln(206, "net.nim");
	(*result0).domain = domain0;
	nimln(207, "net.nim");
	(*result0).socktype = socktype0;
	nimln(208, "net.nim");
	(*result0).protocol = protocol0;
	nimln(209, "net.nim");
	{
		if (!buffered0) goto LA8;
		nimln(210, "net.nim");
		if (!(((2 &(1U<<((NU)((*result0).isbuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &T170061329_7));
		(*result0).isbufferedU.S1.currpos = ((NI) 0);
	}
	LA8: ;
	nimln(214, "net.nim");
	setsockoptint_151831_466562973(fd0, ((NI) (SOL_SOCKET)), ((NI) (SO_NOSIGPIPE)), ((NI) 1));
	popFrame();
	return result0;
}

N_NIMCALL(Socketimpl158406*, newsocket_159009_170061329)(Domain147604 domain0, Socktype147606 socktype0, Protocol147608 protocol0, NIM_BOOL buffered0) {
	Socketimpl158406* result0;
	int fd0;
	nimfr("newSocket", "net.nim")
	result0 = (Socketimpl158406*)0;
	nimln(231, "net.nim");
	fd0 = newnativesocket_148001_466562973(domain0, socktype0, protocol0);
	nimln(232, "net.nim");
	{
		NI32 LOC5;
		if (!(fd0 == osinvalidsocket_147651_466562973)) goto LA3;
		nimln(233, "net.nim");
		LOC5 = (NI32)0;
		LOC5 = oslasterror_130619_2125978480();
		raiseoserror_130603_2125978480(LOC5, ((NimStringDesc*) &T170061329_5));
	}
	LA3: ;
	nimln(234, "net.nim");
	result0 = newsocket_158674_170061329(fd0, domain0, socktype0, protocol0, buffered0);
	popFrame();
	return result0;
}

N_NIMCALL(void, bindaddr_159808_170061329)(Socketimpl158406* socket0, NU16 port0, NimStringDesc* address0) {
	nimfr("bindAddr", "net.nim")
	nimln(551, "net.nim");
	{
		struct sockaddr_in name0;
		if (!((address0) && (address0)->Sup.len == 0)) goto LA3;
		memset((void*)(&name0), 0, sizeof(name0));
		nimln(556, "net.nim");
		name0.sin_family = toint_147820_466562973(((Domain147604) 2));
		nimln(557, "net.nim");
		nimln(285, "nativesockets.nim");
		name0.sin_port = ntohs_149088_466562973(port0);
		nimln(558, "net.nim");
		nimln(270, "nativesockets.nim");
		name0.sin_addr.s_addr = ntohl_148806_466562973(INADDR_ANY);
		nimln(559, "net.nim");
		{
			int LOC7;
			NI32 LOC10;
			nimln(560, "net.nim");
			nimln(559, "net.nim");
			nimln(560, "net.nim");
			LOC7 = (int)0;
			LOC7 = bindaddr_148208_466562973((*socket0).fd, ((struct sockaddr*) ((&name0))), ((socklen_t) (((NI)sizeof(struct sockaddr_in)))));
			if (!(LOC7 < ((NI32) 0))) goto LA8;
			nimln(561, "net.nim");
			LOC10 = (NI32)0;
			LOC10 = oslasterror_130619_2125978480();
			raiseoserror_130603_2125978480(LOC10, ((NimStringDesc*) &T170061329_5));
		}
		LA8: ;
	}
	goto LA1;
	LA3: ;
	{
		struct addrinfo* ailist0;
		nimln(563, "net.nim");
		ailist0 = getaddrinfo_148402_466562973(address0, port0, (*socket0).domain, ((Socktype147606) 1), ((Protocol147608) 6));
		nimln(564, "net.nim");
		{
			int LOC14;
			NI32 LOC17;
			LOC14 = (int)0;
			LOC14 = bindaddr_148208_466562973((*socket0).fd, (*ailist0).ai_addr, (*ailist0).ai_addrlen);
			if (!(LOC14 < ((NI32) 0))) goto LA15;
			nimln(565, "net.nim");
			dealloc_148802_466562973(ailist0);
			nimln(566, "net.nim");
			LOC17 = (NI32)0;
			LOC17 = oslasterror_130619_2125978480();
			raiseoserror_130603_2125978480(LOC17, ((NimStringDesc*) &T170061329_5));
		}
		LA15: ;
		nimln(567, "net.nim");
		dealloc_148802_466562973(ailist0);
	}
	LA1: ;
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NI, sendto_163821_170061329)(Socketimpl158406* socket0, NimStringDesc* address0, NU16 port0, void* data0, NI size0, Domain147604 af0, NI32 flags0) {
	NI result0;
	struct addrinfo* ailist0;
	NIM_BOOL success0;
	struct addrinfo* it0;
	nimfr("sendTo", "net.nim")
	result0 = (NI)0;
	nimln(1185, "net.nim");
	ailist0 = getaddrinfo_148402_466562973(address0, port0, af0, ((Socktype147606) 1), ((Protocol147608) 6));
	nimln(1188, "net.nim");
	success0 = NIM_FALSE;
	nimln(1189, "net.nim");
	it0 = ailist0;
	{
		nimln(1190, "net.nim");
		while (1) {
			nimln(347, "system.nim");
			if (!!((it0 == NIM_NIL))) goto LA2;
			nimln(1191, "net.nim");
			result0 = sendto((*socket0).fd, data0, ((NI) (((int)chckRange(size0, ((int) (-2147483647 -1)), ((int) 2147483647))))), flags0, (*it0).ai_addr, (*it0).ai_addrlen);
			nimln(1193, "net.nim");
			{
				nimln(347, "system.nim");
				if (!!((result0 == ((NI) -1)))) goto LA5;
				nimln(1194, "net.nim");
				success0 = NIM_TRUE;
				nimln(1195, "net.nim");
				goto LA1;
			}
			LA5: ;
			nimln(1196, "net.nim");
			it0 = (*it0).ai_next;
		} LA2: ;
	} LA1: ;
	nimln(1198, "net.nim");
	dealloc_148802_466562973(ailist0);
	popFrame();
	return result0;
}

N_NIMCALL(NI, sendto_163849_170061329)(Socketimpl158406* socket0, NimStringDesc* address0, NU16 port0, NimStringDesc* data0) {
	NI result0;
	nimfr("sendTo", "net.nim")
	result0 = (NI)0;
	nimln(1207, "net.nim");
	result0 = sendto_163821_170061329(socket0, address0, port0, ((void*) (data0->data)), (data0 ? data0->Sup.len : 0), ((Domain147604) 2), ((NI32) 0));
	popFrame();
	return result0;
}

N_NIMCALL(NI32, getsocketerror_159201_170061329)(Socketimpl158406* socket0) {
	NI32 result0;
	nimfr("getSocketError", "net.nim")
	result0 = (NI32)0;
	nimln(475, "net.nim");
	result0 = oslasterror_130619_2125978480();
	nimln(476, "net.nim");
	{
		if (!(result0 == ((NI32) 0))) goto LA3;
		nimln(477, "net.nim");
		result0 = (*socket0).lasterror;
	}
	LA3: ;
	nimln(478, "net.nim");
	{
		if (!(result0 == ((NI32) 0))) goto LA7;
		nimln(479, "net.nim");
		raiseoserror_130603_2125978480(result0, ((NimStringDesc*) &T170061329_8));
	}
	LA7: ;
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit000)(void) {
	nimfr("net", "net.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit000)(void) {
static TNimNode* T170061329_2[6];
static TNimNode* T170061329_3[3];
static TNimNode T170061329_0[12];
NTI158406.size = sizeof(Socketimpl158406);
NTI158406.kind = 18;
NTI158406.base = 0;
NTI158406.flags = 3;
T170061329_2[0] = &T170061329_0[1];
T170061329_0[1].kind = 1;
T170061329_0[1].offset = offsetof(Socketimpl158406, fd);
T170061329_0[1].typ = (&NTI7408);
T170061329_0[1].name = "fd";
T170061329_2[1] = &T170061329_0[2];
T170061329_0[2].kind = 3;
T170061329_0[2].offset = offsetof(Socketimpl158406, isbuffered);
T170061329_0[2].typ = (&NTI130);
T170061329_0[2].name = "isBuffered";
T170061329_0[2].sons = &NimDT_158406_isbuffered[0];
T170061329_0[2].len = 2;
T170061329_3[0] = &T170061329_0[4];
NTI158420.size = sizeof(TY158420);
NTI158420.kind = 16;
NTI158420.base = (&NTI136);
NTI158420.flags = 3;
T170061329_0[4].kind = 1;
T170061329_0[4].offset = offsetof(Socketimpl158406, isbufferedU.S1.buffer);
T170061329_0[4].typ = (&NTI158420);
T170061329_0[4].name = "buffer";
T170061329_3[1] = &T170061329_0[5];
T170061329_0[5].kind = 1;
T170061329_0[5].offset = offsetof(Socketimpl158406, isbufferedU.S1.currpos);
T170061329_0[5].typ = (&NTI104);
T170061329_0[5].name = "currPos";
T170061329_3[2] = &T170061329_0[6];
T170061329_0[6].kind = 1;
T170061329_0[6].offset = offsetof(Socketimpl158406, isbufferedU.S1.buflen);
T170061329_0[6].typ = (&NTI104);
T170061329_0[6].name = "bufLen";
T170061329_0[3].len = 3; T170061329_0[3].kind = 2; T170061329_0[3].sons = &T170061329_3[0];
NimDT_158406_isbuffered[1] = &T170061329_0[3];
T170061329_0[7].len = 0; T170061329_0[7].kind = 2;
NimDT_158406_isbuffered[0] = &T170061329_0[7];
T170061329_2[2] = &T170061329_0[8];
T170061329_0[8].kind = 1;
T170061329_0[8].offset = offsetof(Socketimpl158406, lasterror);
T170061329_0[8].typ = (&NTI110);
T170061329_0[8].name = "lastError";
T170061329_2[3] = &T170061329_0[9];
T170061329_0[9].kind = 1;
T170061329_0[9].offset = offsetof(Socketimpl158406, domain);
T170061329_0[9].typ = (&NTI147604);
T170061329_0[9].name = "domain";
T170061329_2[4] = &T170061329_0[10];
T170061329_0[10].kind = 1;
T170061329_0[10].offset = offsetof(Socketimpl158406, socktype);
T170061329_0[10].typ = (&NTI147606);
T170061329_0[10].name = "sockType";
T170061329_2[5] = &T170061329_0[11];
T170061329_0[11].kind = 1;
T170061329_0[11].offset = offsetof(Socketimpl158406, protocol);
T170061329_0[11].typ = (&NTI147608);
T170061329_0[11].name = "protocol";
T170061329_0[0].len = 6; T170061329_0[0].kind = 2; T170061329_0[0].sons = &T170061329_2[0];
NTI158406.node = &T170061329_0[0];
NTI158408.size = sizeof(Socketimpl158406*);
NTI158408.kind = 22;
NTI158408.base = (&NTI158406);
NTI158408.flags = 2;
NTI158408.marker = T170061329_4;
}

