/* Generated by Nim Compiler v0.15.0 */
/*   (c) 2016 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.15.0/nim/lib -o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/stdlib_hashes.o /Users/jceipek/Development/Work/Thesis/nimServer/nimcache/stdlib_hashes.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, HEX21HEX26_154005_213663784)(NI h0, NI val0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21601_1689653243)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, HEX21HEX24_154028_213663784)(NI h0);
N_NIMCALL(NI, hashdata_154050_213663784)(void* data0, NI size0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a0, NI b0);
static N_INLINE(NI, hash_154401_213663784)(void* x0);
static N_INLINE(NI, hash_154801_213663784)(NI x0);
static N_INLINE(NI, hash_154805_213663784)(NI64 x0);
static N_INLINE(NI, hash_154809_213663784)(NIM_CHAR x0);
N_NIMCALL(NI, hash_154827_213663784)(NimStringDesc* x0);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI, hash_154859_213663784)(NimStringDesc* sbuf0, NI spos0, NI epos0);
N_NIMCALL(NI, hashignorestyle_154892_213663784)(NimStringDesc* x0);
static N_INLINE(NIM_BOOL, ismagicidentseparatorrune_153005_3239285623)(NCSTRING cs0, NI i0);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
N_NIMCALL(NI, hashignorestyle_154975_213663784)(NimStringDesc* sbuf0, NI spos0, NI epos0);
N_NIMCALL(NI, hashignorecase_155059_213663784)(NimStringDesc* x0);
N_NIMCALL(NI, hashignorecase_155130_213663784)(NimStringDesc* sbuf0, NI spos0, NI epos0);
static N_INLINE(NI, hash_155202_213663784)(NF x0);
extern TFrame* frameptr_18836_1689653243;

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18836_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18836_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18836_1689653243;
	frameptr_18836_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21601_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18836_1689653243 = (*frameptr_18836_1689653243).prev;
}

static N_INLINE(NI, HEX21HEX26_154005_213663784)(NI h0, NI val0) {
	NI result0;
	nimfr("!&", "hashes.nim")
	result0 = (NI)0;
	nimln(53, "hashes.nim");
	result0 = (NI)((NU64)(h0) + (NU64)(val0));
	nimln(54, "hashes.nim");
	result0 = (NI)((NU64)(result0) + (NU64)((NI)((NU64)(result0) << (NU64)(((NI) 10)))));
	nimln(55, "hashes.nim");
	result0 = (NI)(result0 ^ (NI)((NU64)(result0) >> (NU64)(((NI) 6))));
	popFrame();
	return result0;
}

static N_INLINE(NI, HEX21HEX24_154028_213663784)(NI h0) {
	NI result0;
	nimfr("!$", "hashes.nim")
	result0 = (NI)0;
	nimln(60, "hashes.nim");
	result0 = (NI)((NU64)(h0) + (NU64)((NI)((NU64)(h0) << (NU64)(((NI) 3)))));
	nimln(61, "hashes.nim");
	result0 = (NI)(result0 ^ (NI)((NU64)(result0) >> (NU64)(((NI) 11))));
	nimln(62, "hashes.nim");
	result0 = (NI)((NU64)(result0) + (NU64)((NI)((NU64)(result0) << (NU64)(((NI) 15)))));
	popFrame();
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NI, hashdata_154050_213663784)(void* data0, NI size0) {
	NI result0;
	NI h0;
	NCSTRING p0;
	NI i0;
	NI s0;
	nimfr("hashData", "hashes.nim")
	result0 = (NI)0;
	nimln(66, "hashes.nim");
	h0 = ((NI) 0);
	nimln(71, "hashes.nim");
	p0 = ((NCSTRING) (data0));
	nimln(72, "hashes.nim");
	i0 = ((NI) 0);
	nimln(73, "hashes.nim");
	s0 = size0;
	{
		nimln(74, "hashes.nim");
		while (1) {
			NI T213663784_2;
			NI T213663784_3;
			nimln(355, "system.nim");
			if (!(((NI) 0) < s0)) goto LA2;
			nimln(75, "hashes.nim");
			h0 = HEX21HEX26_154005_213663784(h0, ((NI) (((NU8)(p0[i0])))));
			nimln(76, "hashes.nim");
			T213663784_2 = addInt(i0, ((NI) 1));
			i0 = (NI)(T213663784_2);
			nimln(77, "hashes.nim");
			T213663784_3 = subInt(s0, ((NI) 1));
			s0 = (NI)(T213663784_3);
		} LA2: ;
	}
	nimln(78, "hashes.nim");
	result0 = HEX21HEX24_154028_213663784(h0);
	popFrame();
	return result0;
}

static N_INLINE(NI, hash_154401_213663784)(void* x0) {
	NI result0;
	nimfr("hash", "hashes.nim")
	result0 = (NI)0;
	nimln(97, "hashes.nim");
	result0 = (NI)((NU64)(((NI) (x0))) >> (NU64)(((NI) 3)));
	popFrame();
	return result0;
}

static N_INLINE(NI, hash_154801_213663784)(NI x0) {
	NI result0;
	nimfr("hash", "hashes.nim")
	result0 = (NI)0;
	nimln(109, "hashes.nim");
	result0 = x0;
	popFrame();
	return result0;
}

static N_INLINE(NI, hash_154805_213663784)(NI64 x0) {
	NI result0;
	nimfr("hash", "hashes.nim")
	result0 = (NI)0;
	nimln(113, "hashes.nim");
	result0 = ((NI) (((NI32)(NU32)(NU64)(x0))));
	popFrame();
	return result0;
}

static N_INLINE(NI, hash_154809_213663784)(NIM_CHAR x0) {
	NI result0;
	nimfr("hash", "hashes.nim")
	result0 = (NI)0;
	nimln(117, "hashes.nim");
	result0 = ((NI) (((NU8)(x0))));
	popFrame();
	return result0;
}

N_NIMCALL(NI, hash_154827_213663784)(NimStringDesc* x0) {
	NI result0;
	NI h0;
	nimfr("hash", "hashes.nim")
	result0 = (NI)0;
	nimln(125, "hashes.nim");
	h0 = ((NI) 0);
	{
		NI i_154841_213663784;
		NI HEX3Atmp_154852_213663784;
		NI T213663784_4;
		NI res_154855_213663784;
		i_154841_213663784 = (NI)0;
		HEX3Atmp_154852_213663784 = (NI)0;
		nimln(126, "hashes.nim");
		T213663784_4 = subInt((x0 ? x0->Sup.len : 0), ((NI) 1));
		HEX3Atmp_154852_213663784 = (NI)(T213663784_4);
		nimln(1887, "system.nim");
		res_154855_213663784 = ((NI) 0);
		{
			nimln(1888, "system.nim");
			while (1) {
				NI T213663784_5;
				if (!(res_154855_213663784 <= HEX3Atmp_154852_213663784)) goto LA3;
				nimln(1889, "system.nim");
				i_154841_213663784 = res_154855_213663784;
				nimln(127, "hashes.nim");
				if ((NU)(i_154841_213663784) > (NU)(x0->Sup.len)) raiseIndexError();
				h0 = HEX21HEX26_154005_213663784(h0, ((NI) (((NU8)(x0->data[i_154841_213663784])))));
				nimln(1908, "system.nim");
				T213663784_5 = addInt(res_154855_213663784, ((NI) 1));
				res_154855_213663784 = (NI)(T213663784_5);
			} LA3: ;
		}
	}
	nimln(128, "hashes.nim");
	result0 = HEX21HEX24_154028_213663784(h0);
	popFrame();
	return result0;
}

N_NIMCALL(NI, hash_154859_213663784)(NimStringDesc* sbuf0, NI spos0, NI epos0) {
	NI result0;
	NI h0;
	nimfr("hash", "hashes.nim")
	result0 = (NI)0;
	nimln(135, "hashes.nim");
	h0 = ((NI) 0);
	{
		NI i_154875_213663784;
		NI res_154888_213663784;
		i_154875_213663784 = (NI)0;
		nimln(1887, "system.nim");
		res_154888_213663784 = spos0;
		{
			nimln(1888, "system.nim");
			while (1) {
				NI T213663784_6;
				if (!(res_154888_213663784 <= epos0)) goto LA3;
				nimln(1889, "system.nim");
				i_154875_213663784 = res_154888_213663784;
				nimln(137, "hashes.nim");
				if ((NU)(i_154875_213663784) > (NU)(sbuf0->Sup.len)) raiseIndexError();
				h0 = HEX21HEX26_154005_213663784(h0, ((NI) (((NU8)(sbuf0->data[i_154875_213663784])))));
				nimln(1908, "system.nim");
				T213663784_6 = addInt(res_154888_213663784, ((NI) 1));
				res_154888_213663784 = (NI)(T213663784_6);
			} LA3: ;
		}
	}
	nimln(138, "hashes.nim");
	result0 = HEX21HEX24_154028_213663784(h0);
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, ismagicidentseparatorrune_153005_3239285623)(NCSTRING cs0, NI i0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	NIM_BOOL LOC2;
	NI T213663784_8;
	NI T213663784_9;
	nimfr("isMagicIdentSeparatorRune", "etcpriv.nim")
	result0 = (NIM_BOOL)0;
	nimln(21, "etcpriv.nim");
	nimln(22, "etcpriv.nim");
	LOC1 = (NIM_BOOL)0;
	nimln(21, "etcpriv.nim");
	LOC2 = (NIM_BOOL)0;
	LOC2 = ((NU8)(cs0[i0]) == (NU8)(226));
	if (!(LOC2)) goto LA3;
	nimln(22, "etcpriv.nim");
	T213663784_8 = addInt(i0, ((NI) 1));
	LOC2 = ((NU8)(cs0[(NI)(T213663784_8)]) == (NU8)(128));
	LA3: ;
	LOC1 = LOC2;
	if (!(LOC1)) goto LA4;
	nimln(23, "etcpriv.nim");
	T213663784_9 = addInt(i0, ((NI) 2));
	LOC1 = ((NU8)(cs0[(NI)(T213663784_9)]) == (NU8)(147));
	LA4: ;
	result0 = LOC1;
	popFrame();
	return result0;
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NI, hashignorestyle_154892_213663784)(NimStringDesc* x0) {
	NI result0;
	NI h0;
	NI i0;
	NI xlen0;
	nimfr("hashIgnoreStyle", "hashes.nim")
	result0 = (NI)0;
	nimln(142, "hashes.nim");
	h0 = ((NI) 0);
	nimln(143, "hashes.nim");
	i0 = ((NI) 0);
	nimln(144, "hashes.nim");
	xlen0 = (x0 ? x0->Sup.len : 0);
	{
		nimln(145, "hashes.nim");
		while (1) {
			NIM_CHAR c0;
			if (!(i0 < xlen0)) goto LA2;
			nimln(146, "hashes.nim");
			if ((NU)(i0) > (NU)(x0->Sup.len)) raiseIndexError();
			c0 = x0->data[i0];
			nimln(147, "hashes.nim");
			{
				NI T213663784_7;
				if (!((NU8)(c0) == (NU8)(95))) goto LA5;
				nimln(148, "hashes.nim");
				T213663784_7 = addInt(i0, ((NI) 1));
				i0 = (NI)(T213663784_7);
			}
			goto LA3;
			LA5: ;
			{
				NIM_BOOL LOC8;
				NI T213663784_10;
				nimln(149, "hashes.nim");
				LOC8 = (NIM_BOOL)0;
				LOC8 = ismagicidentseparatorrune_153005_3239285623(x0->data, i0);
				if (!LOC8) goto LA9;
				nimln(150, "hashes.nim");
				T213663784_10 = addInt(i0, ((NI) 3));
				i0 = (NI)(T213663784_10);
			}
			goto LA3;
			LA9: ;
			{
				NI T213663784_12;
				nimln(152, "hashes.nim");
				{
					NI T213663784_11;
					nimln(1105, "system.nim");
					if (!(((NU8)(c0)) >= ((NU8)(65)) && ((NU8)(c0)) <= ((NU8)(90)))) goto LA14;
					nimln(153, "hashes.nim");
					T213663784_11 = addInt(((NI) (((NU8)(c0)))), ((NI) 32));
					c0 = ((NIM_CHAR) (((NI)chckRange((NI)(T213663784_11), ((NI) 0), ((NI) 255)))));
				}
				LA14: ;
				nimln(154, "hashes.nim");
				h0 = HEX21HEX26_154005_213663784(h0, ((NI) (((NU8)(c0)))));
				nimln(155, "hashes.nim");
				T213663784_12 = addInt(i0, ((NI) 1));
				i0 = (NI)(T213663784_12);
			}
			LA3: ;
		} LA2: ;
	}
	nimln(157, "hashes.nim");
	result0 = HEX21HEX24_154028_213663784(h0);
	popFrame();
	return result0;
}

N_NIMCALL(NI, hashignorestyle_154975_213663784)(NimStringDesc* sbuf0, NI spos0, NI epos0) {
	NI result0;
	NI h0;
	NI i0;
	nimfr("hashIgnoreStyle", "hashes.nim")
	result0 = (NI)0;
	nimln(165, "hashes.nim");
	h0 = ((NI) 0);
	nimln(166, "hashes.nim");
	i0 = spos0;
	{
		nimln(167, "hashes.nim");
		while (1) {
			NIM_CHAR c0;
			if (!(i0 <= epos0)) goto LA2;
			nimln(168, "hashes.nim");
			if ((NU)(i0) > (NU)(sbuf0->Sup.len)) raiseIndexError();
			c0 = sbuf0->data[i0];
			nimln(169, "hashes.nim");
			{
				NI T213663784_13;
				if (!((NU8)(c0) == (NU8)(95))) goto LA5;
				nimln(170, "hashes.nim");
				T213663784_13 = addInt(i0, ((NI) 1));
				i0 = (NI)(T213663784_13);
			}
			goto LA3;
			LA5: ;
			{
				NIM_BOOL LOC8;
				NI T213663784_14;
				nimln(171, "hashes.nim");
				LOC8 = (NIM_BOOL)0;
				LOC8 = ismagicidentseparatorrune_153005_3239285623(sbuf0->data, i0);
				if (!LOC8) goto LA9;
				nimln(172, "hashes.nim");
				T213663784_14 = addInt(i0, ((NI) 3));
				i0 = (NI)(T213663784_14);
			}
			goto LA3;
			LA9: ;
			{
				NI T213663784_16;
				nimln(174, "hashes.nim");
				{
					NI T213663784_15;
					nimln(1105, "system.nim");
					if (!(((NU8)(c0)) >= ((NU8)(65)) && ((NU8)(c0)) <= ((NU8)(90)))) goto LA14;
					nimln(175, "hashes.nim");
					T213663784_15 = addInt(((NI) (((NU8)(c0)))), ((NI) 32));
					c0 = ((NIM_CHAR) (((NI)chckRange((NI)(T213663784_15), ((NI) 0), ((NI) 255)))));
				}
				LA14: ;
				nimln(176, "hashes.nim");
				h0 = HEX21HEX26_154005_213663784(h0, ((NI) (((NU8)(c0)))));
				nimln(177, "hashes.nim");
				T213663784_16 = addInt(i0, ((NI) 1));
				i0 = (NI)(T213663784_16);
			}
			LA3: ;
		} LA2: ;
	}
	nimln(178, "hashes.nim");
	result0 = HEX21HEX24_154028_213663784(h0);
	popFrame();
	return result0;
}

N_NIMCALL(NI, hashignorecase_155059_213663784)(NimStringDesc* x0) {
	NI result0;
	NI h0;
	nimfr("hashIgnoreCase", "hashes.nim")
	result0 = (NI)0;
	nimln(182, "hashes.nim");
	h0 = ((NI) 0);
	{
		NI i_155073_213663784;
		NI HEX3Atmp_155123_213663784;
		NI T213663784_17;
		NI res_155126_213663784;
		i_155073_213663784 = (NI)0;
		HEX3Atmp_155123_213663784 = (NI)0;
		nimln(183, "hashes.nim");
		T213663784_17 = subInt((x0 ? x0->Sup.len : 0), ((NI) 1));
		HEX3Atmp_155123_213663784 = (NI)(T213663784_17);
		nimln(1887, "system.nim");
		res_155126_213663784 = ((NI) 0);
		{
			nimln(1888, "system.nim");
			while (1) {
				NIM_CHAR c0;
				NI T213663784_19;
				if (!(res_155126_213663784 <= HEX3Atmp_155123_213663784)) goto LA3;
				nimln(1889, "system.nim");
				i_155073_213663784 = res_155126_213663784;
				nimln(184, "hashes.nim");
				if ((NU)(i_155073_213663784) > (NU)(x0->Sup.len)) raiseIndexError();
				c0 = x0->data[i_155073_213663784];
				nimln(185, "hashes.nim");
				{
					NI T213663784_18;
					nimln(1105, "system.nim");
					if (!(((NU8)(c0)) >= ((NU8)(65)) && ((NU8)(c0)) <= ((NU8)(90)))) goto LA6;
					nimln(186, "hashes.nim");
					T213663784_18 = addInt(((NI) (((NU8)(c0)))), ((NI) 32));
					c0 = ((NIM_CHAR) (((NI)chckRange((NI)(T213663784_18), ((NI) 0), ((NI) 255)))));
				}
				LA6: ;
				nimln(187, "hashes.nim");
				h0 = HEX21HEX26_154005_213663784(h0, ((NI) (((NU8)(c0)))));
				nimln(1908, "system.nim");
				T213663784_19 = addInt(res_155126_213663784, ((NI) 1));
				res_155126_213663784 = (NI)(T213663784_19);
			} LA3: ;
		}
	}
	nimln(188, "hashes.nim");
	result0 = HEX21HEX24_154028_213663784(h0);
	popFrame();
	return result0;
}

N_NIMCALL(NI, hashignorecase_155130_213663784)(NimStringDesc* sbuf0, NI spos0, NI epos0) {
	NI result0;
	NI h0;
	nimfr("hashIgnoreCase", "hashes.nim")
	result0 = (NI)0;
	nimln(196, "hashes.nim");
	h0 = ((NI) 0);
	{
		NI i_155146_213663784;
		NI res_155198_213663784;
		i_155146_213663784 = (NI)0;
		nimln(1887, "system.nim");
		res_155198_213663784 = spos0;
		{
			nimln(1888, "system.nim");
			while (1) {
				NIM_CHAR c0;
				NI T213663784_21;
				if (!(res_155198_213663784 <= epos0)) goto LA3;
				nimln(1889, "system.nim");
				i_155146_213663784 = res_155198_213663784;
				nimln(198, "hashes.nim");
				if ((NU)(i_155146_213663784) > (NU)(sbuf0->Sup.len)) raiseIndexError();
				c0 = sbuf0->data[i_155146_213663784];
				nimln(199, "hashes.nim");
				{
					NI T213663784_20;
					nimln(1105, "system.nim");
					if (!(((NU8)(c0)) >= ((NU8)(65)) && ((NU8)(c0)) <= ((NU8)(90)))) goto LA6;
					nimln(200, "hashes.nim");
					T213663784_20 = addInt(((NI) (((NU8)(c0)))), ((NI) 32));
					c0 = ((NIM_CHAR) (((NI)chckRange((NI)(T213663784_20), ((NI) 0), ((NI) 255)))));
				}
				LA6: ;
				nimln(201, "hashes.nim");
				h0 = HEX21HEX26_154005_213663784(h0, ((NI) (((NU8)(c0)))));
				nimln(1908, "system.nim");
				T213663784_21 = addInt(res_155198_213663784, ((NI) 1));
				res_155198_213663784 = (NI)(T213663784_21);
			} LA3: ;
		}
	}
	nimln(202, "hashes.nim");
	result0 = HEX21HEX24_154028_213663784(h0);
	popFrame();
	return result0;
}

static N_INLINE(NI, hash_155202_213663784)(NF x0) {
	NI result0;
	NF y0;
	nimfr("hash", "hashes.nim")
	result0 = (NI)0;
	nimln(206, "hashes.nim");
	y0 = ((NF)(x0) + (NF)(1.0000000000000000e+00));
	nimln(207, "hashes.nim");
	result0 = (*((NI*) ((&y0))));
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void) {
	nimfr("hashes", "hashes.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void) {
}

